import type {Region} from '../types';
export type SearchResult={id:string;label:string;lat:number;lng:number;provider:'maptiler'|'photon'};
const cache=new Map<string,SearchResult[]>();let fallbackQueue=Promise.resolve();let lastFallback=0;
const bbox=(r:Region)=>[r.bounds.west,r.bounds.south,r.bounds.east,r.bounds.north].join(',');
const within=(x:SearchResult,r:Region)=>x.lng>=r.bounds.west&&x.lng<=r.bounds.east&&x.lat>=r.bounds.south&&x.lat<=r.bounds.north;
async function json(url:string,signal?:AbortSignal){const response=await fetch(url,{signal,headers:{Accept:'application/json'}});if(!response.ok)throw Error(`Geocoder HTTP ${response.status}`);return response.json();}
export async function geocode(query:string,region:Region,options:{key?:string;photonUrl?:string;signal?:AbortSignal}={}):Promise<SearchResult[]>{const q=query.trim();if(q.length<3)return [];const id=`${region.id}:${bbox(region)}:${q.toLowerCase()}`;if(cache.has(id))return cache.get(id)!;let results:SearchResult[]=[];if(options.key){try{const data=await json(`https://api.maptiler.com/geocoding/${encodeURIComponent(q)}.json?key=${encodeURIComponent(options.key)}&bbox=${bbox(region)}&limit=5&autocomplete=true`,options.signal);results=(data.features??[]).map((f:{id:string;place_name:string;center:number[]})=>({id:f.id,label:f.place_name,lng:f.center[0],lat:f.center[1],provider:'maptiler' as const})).filter((x:SearchResult)=>within(x,region));}catch(e){if(options.signal?.aborted)throw e;}}
 if(!results.length){const task=fallbackQueue.catch(()=>{}).then(async()=>{const wait=Math.max(0,1100-(Date.now()-lastFallback));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));options.signal?.throwIfAborted();lastFallback=Date.now();const endpoint=options.photonUrl??'https://photon.komoot.io/api/';const u=new URL(endpoint);u.searchParams.set('q',q);u.searchParams.set('bbox',bbox(region));u.searchParams.set('limit','5');const data=await json(u.href,options.signal);return(data.features??[]).map((f:{geometry:{coordinates:number[]};properties:{osm_id:number;name?:string;city?:string;state?:string}})=>({id:`photon-${f.properties.osm_id}`,label:[f.properties.name,f.properties.city,f.properties.state].filter(Boolean).join(', '),lng:f.geometry.coordinates[0],lat:f.geometry.coordinates[1],provider:'photon' as const})).filter((x:SearchResult)=>within(x,region))});fallbackQueue=task.then(()=>{});results=await task;}
 if(cache.size>100)cache.delete(cache.keys().next().value!);cache.set(id,results);return results;
}
export function clearGeocoderCache(){cache.clear();lastFallback=0;fallbackQueue=Promise.resolve()}
