import {z} from 'zod';
const value=z.number().int().nonnegative().nullable();
const record=z.object({id:z.string(),name:z.string(),year:z.number().int(),count:value,countType:z.literal('recorded_total'),sourceRow:z.number().int(),categories:z.array(z.object({column:z.number().int(),label:z.string(),count:value,kind:z.enum(['subtotal','source_heading']),highlight:z.string().nullable()})),missingColumns:z.array(z.number().int()),categoryMismatches:z.array(z.object({column:z.number().int(),label:z.string(),reported_parent:value,child_sum:value,difference:z.number().nullable()})),reference:z.object({coordinates:z.tuple([z.number().min(76.8).max(77.4),z.number().min(28.4).max(28.9)]),name:z.string(),kind:z.string(),source:z.string().url(),assignmentSource:z.string().url(),status:z.literal('approximate_reference'),reviewedAt:z.string()})});
const schema=z.object({schemaVersion:z.literal(1),year:z.number().int(),sourceUrl:z.string().url(),reportUrl:z.string().url(),workbookSha256:z.string().regex(/^[a-f0-9]{64}$/),provenanceNote:z.string(),stateTotal:value,geographicTotal:value,specialUnitTotal:value,referenceNote:z.string(),records:z.array(record).length(15)});
export type HistoricalDistrict=z.infer<typeof record>;
export type HistoricalDistricts=z.infer<typeof schema>;
export function loadHistoricalDistricts(input:unknown){const data=schema.parse(input);if(new Set(data.records.map(r=>r.id)).size!==15||data.records.some(r=>r.id!==r.name||r.year!==data.year))throw Error('Invalid district identity');if(data.records.some(r=>r.categories.length!==64||new Set(r.categories.map(c=>c.column)).size!==64||r.categories.some(c=>c.column<3||c.column>66)||JSON.stringify(r.categories.filter(c=>c.count===null).map(c=>c.column))!==JSON.stringify(r.missingColumns)))throw Error('Invalid category scope');const total=data.records.some(r=>r.count===null)?null:data.records.reduce((n,r)=>n+r.count!,0);if(total!==data.geographicTotal||(total!==null&&data.specialUnitTotal!==null&&total+data.specialUnitTotal!==data.stateTotal))throw Error('Invalid reconciliation');return data}
export function districtDiameter(count:number|null){if(count===null)return null;if(!Number.isFinite(count)||count<0)throw Error('Invalid count');return 22+Math.sqrt(count/1500)*30}
export function districtBand(count:number|null){return count===null?'unknown':count<500?'pale':count<1000?'medium':'strong'}
