import {z} from 'zod';
import {distance,point} from '@turf/turf';
import type {UserPosition} from '../types';
const value=z.number().finite().nonnegative().nullable();
const record=z.object({id:z.string(),name:z.string(),coordinates:z.tuple([z.number().min(76.81).max(77.75),z.number().min(28.27).max(28.91)]),density:value,population:value,reportedCases:z.null(),traffic:z.object({weekday:z.array(value).length(6),weekend:z.array(value).length(6)}),trafficSegments:z.number().int().nonnegative(),cellId:z.string(),referenceStatus:z.literal('user-supplied-unverified'),geometry:z.object({type:z.literal('Polygon'),coordinates:z.array(z.array(z.tuple([z.number(),z.number()])).min(4)).min(1)})});
export const localitySchema=z.object({schemaVersion:z.literal(1),regionId:z.literal('delhi-ncr'),trafficPeriod:z.string(),trafficMeaning:z.string(),populationNote:z.string(),licence:z.string(),geometryNote:z.string(),records:z.array(record)});
export type Locality=z.infer<typeof record>;
export type LocalityContext=z.infer<typeof localitySchema>;
export function currentPeriod(now=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'numeric',hourCycle:'h23',weekday:'short'}).formatToParts(now);return {band:Math.floor(Number(parts.find(p=>p.type==='hour')?.value)/4),day:['Sat','Sun'].includes(parts.find(p=>p.type==='weekday')?.value??'')?'weekend':'weekday' as 'weekend'|'weekday'};}
export function nearestReference(user:UserPosition,records:Locality[]){let best:Locality|null=null,km=Infinity;for(const r of records){const d=distance(point([user.lng,user.lat]),point(r.coordinates),{units:'kilometers'});if(d<km){best=r;km=d;}}return km<=1?{record:best!,km}:null;}
// A separate activity illustration. No crime prediction or cases are imputed.
export function activityScenario(r:Locality,band:number,day:string,references:Locality[]=[]){const probes=r.traffic[day==='weekend'?'weekend':'weekday'][band];if(probes===null||probes===undefined)return null;const night=[.8,.5,.2,.2,.4,1][band];const activity=1/(1+Math.log1p(probes));const densities=references.map(x=>x.density).filter((v):v is number=>v!==null);const densityFactor=r.density!==null&&densities.length>1?1-.1*(densities.filter(v=>v<=r.density!).length/densities.length):1;return Math.round(100*(.55*night+.45*activity)*densityFactor);}
export function contextCells(records:Locality[],band:number,day:string){const groups=new Map<string,Locality[]>();for(const r of records)groups.set(r.cellId,[...(groups.get(r.cellId)??[]),r]);return {type:'FeatureCollection' as const,features:[...groups.values()].map(group=>{const scores=group.map(r=>activityScenario(r,band,day,records)).filter((s):s is number=>s!==null);return {type:'Feature' as const,geometry:group[0].geometry,properties:{id:group[0].id,name:group.map(r=>r.name).join(', '),score:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null}};})};}
export function locationAdvice(r:Locality|null,band:number,day:string='weekday'){const night=band===0||band===5;const probes=r?.traffic[day==='weekend'?'weekend':'weekday'][band];const context=probes===null||probes===undefined?'Road activity is unknown here.':`August 2024 samples average ${probes.toFixed(1)} probes per road-segment-hour in this time band; this is not live traffic.${probes<2?' Those samples show limited recorded activity; consider checking your pickup or route before setting out.':''}`;return `${r?`Near the supplied ${r.name} reference. `:''}${context} ${night?'For travel at this hour, consider well-lit main roads and a licensed ride.':'Choose a route you feel comfortable with and check your pickup point before travelling.'} ${r?.population!==null&&r?.population!==undefined?`The matched population record is ${r.population.toLocaleString('en-IN')} (year unverified); it does not tell us how busy the street is now. `:''}Share your journey with someone you trust if helpful, and keep 112 available. Local crime counts and calibrated risk remain unknown.`;}
