import type {Map as GLMap,ExpressionSpecification,StyleSpecification,FilterSpecification} from 'maplibre-gl';
import type {RiskRecord,Region} from '../types';
import {getScore} from './risk';
export const riskSource='kaali-risk';
export const riskLayers=['kaali-glow','kaali-fill','kaali-pattern','kaali-outline','kaali-3d'];
// Tile archives contain all cities. Filter every layer by the reviewed metadata
// IDs as well as filtering GeoJSON, including an explicit empty selection.
export function filterRisk(map:Pick<GLMap,'getLayer'|'setFilter'>,records:RiskRecord[]){
  const filter:FilterSpecification=records.length
    ? ['in',['get','id'],['literal',records.map(r=>r.id)]]
    : ['==',['literal',1],0];
  for(const id of riskLayers)if(map.getLayer(id))map.setFilter(id,filter);
}
export const riskExpression:ExpressionSpecification=['case',['boolean',['feature-state','known'],false],['interpolate',['linear'],['coalesce',['feature-state','score'],0],0,'#f4b6c3',25,'#e77b92',50,'#c93958',75,'#a62344',100,'#710c2d'],'#838c93'];
export function featureTarget(id:string,region:Region,sample:boolean){return {source:riskSource,id,...(region.pmtiles&&!sample?{sourceLayer:region.sourceLayer??'neighbourhoods'}:{})};}
export function selectFeature(map:Pick<GLMap,'setFeatureState'>,region:Region,sample:boolean,previous:string|null,next:string|null){if(previous)map.setFeatureState(featureTarget(previous,region,sample),{selected:false});if(next)map.setFeatureState(featureTarget(next,region,sample),{selected:true});}
export function restoreRisk(map:GLMap,region:Region,records:RiskRecord[],sample:boolean){if(!map.getSource(riskSource)){map.addSource(riskSource,region.pmtiles&&!sample?{type:'vector',url:`pmtiles://${new URL(region.pmtiles,location.origin).href}`,promoteId:'id'}:{type:'geojson',data:{type:'FeatureCollection',features:records.map(r=>({type:'Feature',id:r.id,geometry:r.geometry,properties:{id:r.id,name:r.name}}))},promoteId:'id'});}if(!map.hasImage('kaali-hatch')){const width=8,data=new Uint8Array(width*width*4);for(let y=0;y<width;y++)for(let x=0;x<width;x++){const p=(y*width+x)*4;data[p]=255;data[p+1]=255;data[p+2]=255;data[p+3]=(x+y)%8<2?170:0;}map.addImage('kaali-hatch',{width,height:width,data});}const common={source:riskSource,...(region.pmtiles&&!sample?{'source-layer':region.sourceLayer??'neighbourhoods'}:{})};if(!map.getLayer('kaali-glow'))map.addLayer({id:'kaali-glow',type:'line',...common,paint:{'line-color':'#e33360','line-width':12,'line-blur':10,'line-opacity':['case',['all',['boolean',['feature-state','known'],false],['>=',['coalesce',['feature-state','score'],0],50]],.22,0]}});if(!map.getLayer('kaali-fill'))map.addLayer({id:'kaali-fill',type:'fill',...common,paint:{'fill-color':riskExpression,'fill-opacity':['case',['boolean',['feature-state','hover'],false],.78,.55],'fill-color-transition':{duration:280},'fill-opacity-transition':{duration:220}}});if(!map.getLayer('kaali-pattern'))map.addLayer({id:'kaali-pattern',type:'fill',...common,paint:{'fill-pattern':'kaali-hatch','fill-opacity':['case',['all',['boolean',['feature-state','known'],false],['>=',['coalesce',['feature-state','score'],0],50]],.5,0]}});if(!map.getLayer('kaali-outline'))map.addLayer({id:'kaali-outline',type:'line',...common,paint:{'line-color':['case',['boolean',['feature-state','selected'],false],'#f9faff',riskExpression],'line-width':['case',['boolean',['feature-state','selected'],false],3,['boolean',['feature-state','hover'],false],2,1],'line-opacity':.9}});if(!map.getLayer('kaali-3d'))map.addLayer({id:'kaali-3d',type:'fill-extrusion',...common,layout:{visibility:'none'},paint:{'fill-extrusion-color':riskExpression,'fill-extrusion-height':['*',['coalesce',['feature-state','score'],0],8],'fill-extrusion-opacity':.72,'fill-extrusion-height-transition':{duration:280}}});}
export function applyScores(map:Pick<GLMap,'setFeatureState'>,region:Region,records:RiskRecord[],sample:boolean,band:number,day:string,crime:string,year:string){for(const r of records){const score=getScore(r,band,day,crime,year);map.setFeatureState(featureTarget(r.id,region,sample),{score:score??0,known:score!==null});}}
export function baseStyle(theme:string,key:string):string|StyleSpecification {if(!key)return {version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':theme==='dark'?'#131e29':'#e3e8e9'}}]};const style=theme==='dark'?(import.meta.env.VITE_MAPTILER_DARK_STYLE||'dataviz-v4-dark'):(import.meta.env.VITE_MAPTILER_LIGHT_STYLE||'dataviz-v4-light');return `https://api.maptiler.com/maps/${encodeURIComponent(style)}/style.json?key=${encodeURIComponent(key)}`;}


