import {z} from 'zod';
import type {Locality} from './locality-context';
import {activityScenario} from './locality-context';
const number=z.number().finite().nonnegative();
export const mlVolumeSchema=z.object({version:z.literal('ml-volume-v1'),model:z.enum(['poisson_glm','lightgbm_poisson']),forecastYear:z.literal(2026),notASafetyProbability:z.literal(true),forecastStatus:z.string(),trainedOn:z.string(),modelSha256:z.string().regex(/^[a-f0-9]{64}$/),assumptions:z.array(z.string()),limitations:z.array(z.string()),anchors:z.array(z.object({id:z.string(),name:z.string(),recordedYear:z.literal(2024),recordedCases:number,forecastYear:z.literal(2026),expectedAnnualCases:number,volume_index:number.max(100),confidence:z.literal('low'),dataType:z.literal('model-estimate')})).length(19),localities:z.array(z.object({id:z.string(),annualVolumeIndex:number.max(100).nullable(),riskScore:z.null(),reportedCases:z.null(),confidence:z.literal('low'),spatialMapping:z.string(),status:z.enum(['unknown','model-reference-interpolation'])}))}).superRefine((data,ctx)=>{if(new Set(data.anchors.map(a=>a.id)).size!==19||new Set(data.localities.map(r=>r.id)).size!==data.localities.length||data.localities.some(r=>(r.status==='unknown')!==(r.annualVolumeIndex===null)))ctx.addIssue({code:'custom',message:'Invalid model coverage or missing-index status'});});
export type MLVolume=z.infer<typeof mlVolumeSchema>;
export function modelRiskLevel(score:number|null):'Low'|'Medium'|'High'|'Very high'|'Unknown'{
 if(score===null||!Number.isFinite(score)||score<0||score>100)return 'Unknown';
 return score<25?'Low':score<50?'Medium':score<75?'High':'Very high';
}
export function mlIndex(model:MLVolume|null,r:Locality,band:number,day:string,references:Locality[]){const annual=model?.localities.find(x=>x.id===r.id)?.annualVolumeIndex;const context=activityScenario(r,band,day,references);if(annual===null||annual===undefined||context===null)return null;return Math.round(Math.min(100,annual*(.75+.5*context/100)));}
export function mlCells(model:MLVolume|null,records:Locality[],band:number,day:string){const groups=new Map<string,Locality[]>();for(const r of records)groups.set(r.cellId,[...(groups.get(r.cellId)??[]),r]);return {type:'FeatureCollection' as const,features:[...groups.values()].map(group=>{const values=group.map(r=>mlIndex(model,r,band,day,records)).filter((v):v is number=>v!==null);return {type:'Feature' as const,geometry:group[0].geometry,properties:{id:group[0].id,name:group.map(r=>r.name).join(', '),score:values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null}};})};}
