import {z} from 'zod';
import type {Level,RiskRecord} from '../types';
export const bands=['00:00–04:00','04:00–08:00','08:00–12:00','12:00–16:00','16:00–20:00','20:00–24:00'];
export const scoreSchema=z.number().finite().min(0).max(100);
const point=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)]);
const ring=z.array(point).min(4).refine(r=>r[0][0]===r[r.length-1][0]&&r[0][1]===r[r.length-1][1],'Unclosed polygon');
export const riskSchema=z.object({id:z.string().min(1),name:z.string(),cityId:z.string(),regionId:z.string(),geometry:z.discriminatedUnion('type',[z.object({type:z.literal('Polygon'),coordinates:z.array(ring).min(1)}),z.object({type:z.literal('MultiPolygon'),coordinates:z.array(z.array(ring).min(1)).min(1)})]),provenance:z.enum(['sample','model','unavailable']),boundaryStatus:z.enum(['sample','verified']),confidence:z.enum(['low','medium','high']),sources:z.array(z.object({label:z.string(),url:z.string().url()})),scores:z.record(z.array(scoreSchema).length(6).nullable()),incidents:z.array(z.object({category:z.string(),count:z.number().nonnegative()})).nullable(),trend:z.array(z.object({year:z.number().int(),count:z.number().nonnegative()})).nullable(),year:z.number().int().nullable(),femalePopulation:z.number().positive().nullable(),periodDays:z.number().positive().nullable(),estimated:z.boolean()}).superRefine((v,c)=>{if(v.provenance==='model'&&(v.boundaryStatus!=='verified'||!v.sources.length||!v.femalePopulation||!v.periodDays))c.addIssue({code:'custom',message:'Model records require verified boundaries, sources and exposure'});if(v.provenance==='unavailable'&&Object.values(v.scores).some(x=>x!==null))c.addIssue({code:'custom',message:'Unavailable data cannot have scores'});});
export function loadRisk(data:unknown):RiskRecord[]{const records=z.array(riskSchema).parse(data);if(new Set(records.map(x=>x.id)).size!==records.length)throw Error('Duplicate zone IDs');return records;}
export function level(score:number):Level {scoreSchema.parse(score);return score<25?'Low':score<50?'Moderate':score<75?'High':'Very High';}
export function displayLevel(score:number|null){return score===null?'Insufficient data':score<25?'Lower estimated risk':`${level(score)} estimated risk`;}
export function getScore(r:RiskRecord,band:number,day:string,crime='all',year='all'):number|null {if(year!=='all'&&String(r.year)!==year)return null;return r.scores[`${day}:${crime}`]?.[band]??null;}
export const riskColor=(s:number|null)=>s===null?'#838c93':s<25?'#f6b7b5':s<50?'#ec777a':s<75?'#cc3e50':'#8e1730';
export function timeContext(timezone:string,date=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',weekday:'short',hourCycle:'h23'}).formatToParts(date);const hour=Number(parts.find(p=>p.type==='hour')!.value);const weekday=parts.find(p=>p.type==='weekday')!.value;return {band:Math.floor(hour/4),day:['Sat','Sun'].includes(weekday)?'weekend':'weekday'};}
export function contains(r:RiskRecord,lng:number,lat:number){const inRing=(ring:number[][])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>lat)!==(yj>lat)&&lng<(xj-xi)*(lat-yi)/(yj-yi)+xi)inside=!inside;}return inside;};const polygons=r.geometry.type==='Polygon'?[r.geometry.coordinates]:r.geometry.coordinates;return polygons.some(poly=>inRing(poly[0])&&!poly.slice(1).some(inRing));}
