import {lazy,Suspense,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Search,ArrowUpRight,MapPin,Info,Phone,ArrowRight,ChevronDown,SlidersHorizontal,Layers} from 'lucide-react';
import {Button,Glass,Skeleton} from '../components/ui';
import {loadHistoricalDistricts,type HistoricalDistricts,districtBand} from '../lib/historical-districts';
import {formatCases} from '../lib/district-crime';
import '../historical-map.css';
import type {Region} from '../types';
const Canvas=lazy(()=>import('../components/HistoricalMapCanvas'));

export default function HistoricalMap({theme,region}:{theme:string;region:Region}){
 const [openPanel,setOpenPanel]=useState<'districts'|'details'|'legend'|null>(null);
 const toggle=(panel:'districts'|'details'|'legend')=>setOpenPanel(current=>current===panel?null:panel);
 const selectDistrict=(id:string)=>{setSelectedId(id);setOpenPanel('details')};
 const [data,setData]=useState<HistoricalDistricts|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/data/delhi-historical-districts.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Historical records could not load');return r.json();}).then(raw=>setData(loadHistoricalDistricts(raw))).catch(e=>{if(!controller.signal.aborted)setError(String(e.message));});return()=>controller.abort();},[]);
 const selected=data?.records.find(r=>r.id===selectedId),filtered=data?.records.filter(r=>r.name.toLowerCase().includes(query.trim().toLowerCase()))??[];
 const highlights=selected?.categories.filter(c=>c.highlight)??[],maximum=Math.max(1,...highlights.map(c=>c.count??0));
 const city=region.cities.find(c=>c.id==='delhi');
 return <main id="main" onKeyDown={e=>{if(e.key==='Escape'&&openPanel){document.getElementById(`${openPanel}-toggle`)?.focus();setOpenPanel(null);e.stopPropagation();}}} className={`historical-layout ${selected?'with-district':''} ${openPanel?`panel-${openPanel}-open`:''}`}>
 <div className="historical-basemap" aria-label="Interactive Delhi historical recorded-case map">{data?<Suspense fallback={<Skeleton/>}><Canvas districts={filtered} selectedId={selectedId} theme={theme} onSelect={selectDistrict} openPanel={openPanel} bounds={city?.bounds??region.bounds} center={city?.center??region.center}/></Suspense>:<div className="historical-loading"><Skeleton/><p role="status">{error||'Loading source-backed district records…'}</p>{error&&<Button onClick={()=>window.location.reload()}>Retry</Button>}</div>}</div>
 <Glass className={`historical-sidebar historical-capsule ${openPanel==='districts'?'is-open':''}`} aria-label="Delhi district controls"><button id="districts-toggle" className="historical-capsule-trigger" onClick={()=>toggle('districts')} aria-expanded={openPanel==='districts'} aria-controls="district-controls-body"><SlidersHorizontal size={18}/><span><strong>{formatCases(data?.geographicTotal)} recorded cases</strong><small>Delhi · {data?.year??2024} · Districts</small></span><ChevronDown size={17}/></button><div id="district-controls-body" className="historical-capsule-body" hidden={openPanel!=='districts'}><p className="eyebrow">DELHI · RECORDED CASES</p><h1>The district<br/>picture.</h1><p className="historical-intro">Crimes against women, as recorded in <strong>{data?.year??'2024'}</strong>. Historical volume, with the source in view.</p>
 <label className="historical-search"><Search size={17}/><span className="sr-only">Search police districts</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a police district" type="search"/></label>
 <div className="historical-scope"><span>{data?.records.length??'—'} police districts</span><strong>{formatCases(data?.geographicTotal)}</strong><small>Recorded geographic-district total · {data?.year??2024}</small></div>
 <div className="historical-district-list" aria-label="Police districts">{filtered.map(d=><button key={d.id} onClick={()=>selectDistrict(d.id)} aria-pressed={d.id===selectedId} className={d.id===selectedId?'selected':''}><span><i className={`historical-dot band-${districtBand(d.count)}`}/>{d.name}</span><strong>{formatCases(d.count)}</strong></button>)}{data&&!filtered.length&&<p>No district matches. <button onClick={()=>setQuery('')}>Clear search</button></p>}</div>
 <p className="historical-awareness"><Info size={15}/>Recorded volume does not establish current safety.</p><Link className="historical-method-link" to="/methodology">Sources & methodology <ArrowUpRight size={15}/></Link><Link className="historical-method-link" to="/neighbourhoods">Neighbourhood experience <ArrowRight size={15}/></Link></div></Glass>
 {selected&&data&&<Glass className={`historical-details historical-capsule ${openPanel==='details'?'is-open':''}`} aria-label="Selected police district details"><button id="details-toggle" className="historical-capsule-trigger" onClick={()=>toggle('details')} aria-expanded={openPanel==='details'} aria-controls="district-details-body"><MapPin size={18}/><span><strong>{selected.name}</strong><small>{formatCases(selected.count)} recorded cases · {selected.year}</small></span><ChevronDown size={17}/></button><div id="district-details-body" className="historical-capsule-body" hidden={openPanel!=='details'}><h2>{selected.name}</h2><div className="historical-total"><strong>{formatCases(selected.count)}</strong><span>Recorded total crimes against women<br/>{selected.year} · IPC/BNS + SLL</span></div>
 <p className="historical-reference"><MapPin size={16}/>Approximate reference: {selected.reference.name} ({selected.reference.kind}). This is not an incident location or a district boundary.</p>
 <h3>Selected crime groups</h3><p className="historical-small">Source categories shown individually. Do not add these to their child categories or to the recorded total.</p><div className="historical-breakdown">{highlights.map(c=><div key={c.column}><div className="historical-bar-heading"><span>{c.highlight}</span><strong>{formatCases(c.count)}</strong></div>{c.count!==null&&<div className="historical-bar-track"><span style={{width:`${c.count/maximum*100}%`}}/></div>}</div>)}</div>
 <details className="historical-category-table"><summary>All source headings & subcategories ({selected.categories.length})</summary><table><caption>Original worksheet columns; totals and components must not be added together</caption><tbody>{selected.categories.map(c=><tr key={c.column}><th scope="row">{c.label}</th><td>{formatCases(c.count)}</td></tr>)}</tbody></table></details>
 <h3>Missing data & source checks</h3><p className="historical-small">{selected.missingColumns.length?`Missing source columns: ${selected.missingColumns.join(', ')}. Blanks remain missing.`:'No blank category cells in this district’s 2024 worksheet row. This does not establish complete crime reporting.'}</p>{selected.categoryMismatches.map(c=><p key={c.column} className="historical-data-note">{c.label}: source parent {formatCases(c.reported_parent)}, children {formatCases(c.child_sum)}. Retained as published; no repair or redistribution.</p>)}
 <a href={data.sourceUrl} target="_blank" rel="noreferrer">NCRB source catalogue <ArrowUpRight size={14}/></a><a href={data.reportUrl} target="_blank" rel="noreferrer">Original report · state-total reconciliation <ArrowUpRight size={14}/></a><a href={selected.reference.source} target="_blank" rel="noreferrer">OSM reference place <ArrowUpRight size={14}/></a><a href={selected.reference.assignmentSource} target="_blank" rel="noreferrer">Delhi Police district directory <ArrowUpRight size={14}/></a><p className="historical-small">{data.provenanceNote}</p>
 <div className="historical-help"><a href="tel:112"><Phone size={16}/> Emergency · call 112</a><Link to="/helplines">Official helplines & government links <ArrowUpRight size={14}/></Link><Link to="/methodology">Sources & methodology <ArrowUpRight size={14}/></Link><Button variant="ghost" size="small" onClick={()=>{setSelectedId(null);setOpenPanel(null);document.getElementById('districts-toggle')?.focus();}}>Clear district selection</Button></div></div></Glass>}
 <Glass className={`historical-legend historical-capsule ${openPanel==='legend'?'is-open':''}`} aria-label="Historical recorded volume legend"><button id="legend-toggle" className="historical-capsule-trigger" onClick={()=>toggle('legend')} aria-expanded={openPanel==='legend'} aria-controls="historical-legend-body"><Layers size={18}/><span><strong>Map legend</strong><small>{data?.year??2024} · Colour & size</small></span><ChevronDown size={17}/></button><div id="historical-legend-body" className="historical-capsule-body" hidden={openPanel!=='legend'}><h2>Recorded cases · {data?.year??2024}</h2><div><span><i className="historical-dot band-pale"/>Under 500</span><span><i className="historical-dot band-medium"/>500–999</span><span><i className="historical-dot band-strong"/>1,000+</span></div><p>Larger circle = more recorded cases. Size: 22 + √(cases ÷ 1,500) × 30 px.</p><small>Historical reporting, not current safety. Display bands only · not NCRB danger classifications. Approximate reference points; no danger radii.</small><Link className="historical-legend-method" to="/methodology">Methodology & sources <ArrowUpRight size={13}/></Link></div></Glass>
 </main>;
}
