import {lazy,Suspense,useEffect,useState,useMemo,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {Search,ArrowUpRight,MapPin,Info,Phone,ArrowRight,ChevronDown,SlidersHorizontal,Layers} from 'lucide-react';
import {Button,Glass,Skeleton} from '../components/ui';
import {districtBand} from '../lib/historical-districts';
import {loadNcrDistricts,type NcrDistricts} from '../lib/ncr-districts';
import {localHour} from '../lib/advisory-risk';
import {mapLayouts,type BasemapLayout} from '../lib/map-layouts';
import LocalAwareness from '../components/LocalAwareness';
import {mlVolumeSchema,type MLVolume} from '../lib/ml-volume';
import {localitySchema,type LocalityContext} from '../lib/locality-context';
import {formatCases} from '../lib/district-crime';
import '../historical-map.css';
import type {Region,HelpFeature,UserPosition} from '../types';
const Canvas=lazy(()=>import('../components/HistoricalMapCanvas'));

export default function HistoricalMap({theme,region}:{theme:string;region:Region}){
 const [ml,setML]=useState<MLVolume|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/data/delhi-ncr/ml-volume.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(raw=>setML(mlVolumeSchema.parse(raw))).catch(()=>setML(null));return()=>controller.abort()},[]);
 const [context,setContext]=useState<LocalityContext|null>(null),[user,setUser]=useState<UserPosition|null>(null),[focusRequest,setFocusRequest]=useState(0);
 const onPosition=useCallback((u:UserPosition|null)=>setUser(u),[]);
 useEffect(()=>{const controller=new AbortController();fetch('/data/delhi-ncr/locality-context.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(raw=>setContext(localitySchema.parse(raw))).catch(()=>setContext(null));return()=>controller.abort()},[]);
 const [help,setHelp]=useState<HelpFeature[]>([]),[layout,setLayout]=useState<BasemapLayout>('streets'),[selectedHour,setSelectedHour]=useState<number|null>(null),[clock,setClock]=useState(()=>new Date()),[visibleKinds,setVisibleKinds]=useState<HelpFeature['properties']['kind'][]>(['police','hospital']);
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),60000);return()=>clearInterval(timer)},[]);
 const hour=selectedHour??localHour(clock,region.timezone),timeBand=Math.floor(hour/4);
 const [openPanel,setOpenPanel]=useState<'districts'|'details'|'legend'|'filters'|null>(null);
 const toggle=(panel:'districts'|'details'|'legend'|'filters')=>setOpenPanel(current=>current===panel?null:panel);
 const selectDistrict=(id:string)=>{setSelectedId(id);setOpenPanel('details')};
 const [data,setData]=useState<NcrDistricts|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/data/ncr-historical-districts.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Historical records could not load');return r.json();}).then(raw=>setData(loadNcrDistricts(raw))).catch(e=>{if(!controller.signal.aborted)setError(String(e.message));});return()=>controller.abort();},[]);
 useEffect(()=>{const controller=new AbortController();fetch(region.helpFile,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(raw=>setHelp(raw.features??[])).catch(()=>setHelp([]));return()=>controller.abort()},[region.helpFile]);
 const selected=data?.records.find(r=>r.id===selectedId);
 const filtered=useMemo(()=>data?.records.filter(r=>`${r.name} ${r.cityId==='gautam-buddh-nagar'?'Noida Greater Noida':''}`.toLowerCase().includes(query.trim().toLowerCase()))??[],[data,query]);
 const highlights=selected?.categories.filter(c=>c.highlight)??[],maximum=Math.max(1,...highlights.map(c=>c.count??0));
 return <main id="main" onKeyDown={e=>{if(e.key==='Escape'&&openPanel){document.getElementById(`${openPanel}-toggle`)?.focus();setOpenPanel(null);e.stopPropagation();}}} className={`historical-layout ${selected?'with-district':''} ${openPanel?`panel-${openPanel}-open`:''}`}>
 <div className="historical-basemap" aria-label="Interactive Delhi NCR historical recorded-case map">{data?<Suspense fallback={<Skeleton/>}><Canvas districts={filtered} selectedId={selectedId} theme={theme} onSelect={selectDistrict} openPanel={openPanel} bounds={region.bounds} center={region.center} help={help} layout={layout} timeBand={timeBand} hour={hour} visibleKinds={visibleKinds} context={context} userPosition={user} focusRequest={focusRequest} ml={ml}/></Suspense>:<div className="historical-loading"><Skeleton/><p role="status">{error||'Loading source-backed district records…'}</p>{error&&<Button onClick={()=>window.location.reload()}>Retry</Button>}</div>}</div>
 <Glass className={`historical-sidebar historical-capsule ${openPanel==='districts'?'is-open':''}`} aria-label="Delhi NCR district controls"><button id="districts-toggle" className="historical-capsule-trigger" onClick={()=>toggle('districts')} aria-expanded={openPanel==='districts'} aria-controls="district-controls-body"><SlidersHorizontal size={18}/><span><strong>{formatCases(data?.ncrRecordedSubtotal)} recorded cases</strong><small>Delhi NCR · {data?.year??2024} · Districts</small></span><ChevronDown size={17}/></button><div id="district-controls-body" className="historical-capsule-body" hidden={openPanel!=='districts'}><p className="eyebrow">DELHI NCR · RECORDED CASES</p><h1>The district<br/>picture.</h1><p className="historical-intro">Crimes against women, as recorded in <strong>{data?.year??'2024'}</strong>. Historical volume, with the source in view.</p>
 <label className="historical-search"><Search size={17}/><span className="sr-only">Search reporting units</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a police district" type="search"/></label>
 <div className="historical-scope"><span>{data?.records.length??'—'} reporting units</span><strong>{formatCases(data?.ncrRecordedSubtotal)}</strong><small>Calculated subtotal of selected NCR districts · {data?.year??2024}</small></div>
 <div className="historical-district-list" aria-label="Police districts">{filtered.map(d=><button key={d.id} onClick={()=>selectDistrict(d.id)} aria-pressed={d.id===selectedId} className={d.id===selectedId?'selected':''}><span><i className={`historical-dot band-${districtBand(d.count)}`}/>{d.name}</span><strong>{formatCases(d.count)}</strong></button>)}{data&&!filtered.length&&<p>No district matches. <button onClick={()=>setQuery('')}>Clear search</button></p>}</div>
 <p className="historical-awareness"><Info size={15}/>Recorded volume does not establish current safety.</p><Link className="historical-method-link" to="/evidence">Crime data & sources <ArrowUpRight size={15}/></Link><Link className="historical-method-link" to="/neighbourhoods">Neighbourhood experience <ArrowRight size={15}/></Link></div></Glass>
 {selected&&data&&<Glass className={`historical-details historical-capsule ${openPanel==='details'?'is-open':''}`} aria-label="Selected police district details"><button id="details-toggle" className="historical-capsule-trigger" onClick={()=>toggle('details')} aria-expanded={openPanel==='details'} aria-controls="district-details-body"><MapPin size={18}/><span><strong>{selected.name}</strong><small>{formatCases(selected.count)} recorded cases · {selected.year}</small></span><ChevronDown size={17}/></button><div id="district-details-body" className="historical-capsule-body" hidden={openPanel!=='details'}><h2>{selected.name}</h2><div className="historical-total"><strong>{formatCases(selected.count)}</strong><span>Recorded total crimes against women<br/>{selected.year} · IPC/BNS + SLL</span></div>
 <p className="historical-reference"><MapPin size={16}/>Approximate reference: {selected.reference.name} ({selected.reference.kind}). This is not an incident location or a district boundary.</p>
 {selected.cityId==='gautam-buddh-nagar'&&<p className="historical-data-note">One Gautam Buddh Nagar reporting unit covers Noida and Greater Noida. No invented city split.</p>}

 <section className="historical-scenario"><h3>Trained ML annual-volume forecast · 2026</h3><strong>{ml?.anchors.find(a=>a.id===selected.id)?.expectedAnnualCases.toLocaleString('en-IN',{maximumFractionDigits:0})??'Unknown'}</strong><p className="historical-small">Estimated annual reported cases for this police reporting unit, from a fitted Poisson model. Not the measured 2024 total or a current safety prediction. Future-year accuracy is unvalidated; several NCR city holdouts are worse than persistence. The coloured locality cells add assumed reference proximity/time/activity adjustments, without assigning district counts to streets.</p></section>
 <p className="historical-small">Neighbourhood counts and risk remain unknown until matching district boundaries and a reviewed allocation crosswalk are available. This district total is not assigned to nearby streets.</p>
 <h3>Selected crime groups</h3><p className="historical-small">Source categories shown individually. Do not add these to their child categories or to the recorded total.</p><div className="historical-breakdown">{highlights.map(c=><div key={c.column}><div className="historical-bar-heading"><span>{c.highlight}</span><strong>{formatCases(c.count)}</strong></div>{c.count!==null&&<div className="historical-bar-track"><span style={{width:`${c.count/maximum*100}%`}}/></div>}</div>)}</div>
 <details className="historical-category-table"><summary>All source headings & subcategories ({selected.categories.length})</summary><table><caption>Original worksheet columns; totals and components must not be added together</caption><tbody>{selected.categories.map(c=><tr key={c.column}><th scope="row">{c.label}</th><td>{formatCases(c.count)}</td></tr>)}</tbody></table></details>
 <h3>Missing data & source checks</h3><p className="historical-small">{selected.missingColumns.length?`Missing source columns: ${selected.missingColumns.join(', ')}. Blanks remain missing.`:'No blank category cells in this district’s 2024 worksheet row. This does not establish complete crime reporting.'}</p>{selected.categoryMismatches.map(c=><p key={c.column} className="historical-data-note">{c.label}: source parent {formatCases(c.reported_parent)}, children {formatCases(c.child_sum)}. Retained as published; no repair or redistribution.</p>)}
 <a href={data.sourceUrl} target="_blank" rel="noreferrer">NCRB source catalogue <ArrowUpRight size={14}/></a><a href={data.reportUrl} target="_blank" rel="noreferrer">Original report · state-total reconciliation <ArrowUpRight size={14}/></a><a href={selected.reference.source} target="_blank" rel="noreferrer">OSM reference place <ArrowUpRight size={14}/></a><a href={selected.reference.assignmentSource} target="_blank" rel="noreferrer">Official district / locality directory <ArrowUpRight size={14}/></a><p className="historical-small">{data.provenanceNote}</p>
 <div className="historical-help"><a href="tel:112"><Phone size={16}/> Emergency · call 112</a><Link to="/helplines">Official helplines & government links <ArrowUpRight size={14}/></Link><Link to="/evidence">Crime data & sources <ArrowUpRight size={14}/></Link><Button variant="ghost" size="small" onClick={()=>{setSelectedId(null);setOpenPanel(null);document.getElementById('districts-toggle')?.focus();}}>Clear district selection</Button></div></div></Glass>}
 <LocalAwareness center={region.center} timezone={region.timezone} ml={ml} context={context} help={help} user={user} onPosition={onPosition} onLocate={()=>setFocusRequest(n=>n+1)} regional={data?{year:data.year,count:data.ncrRecordedSubtotal}:null}/>
 <Glass className={`historical-legend historical-capsule ${openPanel==='legend'?'is-open':''}`} aria-label="Historical recorded volume legend"><button id="legend-toggle" className="historical-capsule-trigger" onClick={()=>toggle('legend')} aria-expanded={openPanel==='legend'} aria-controls="historical-legend-body"><Layers size={18}/><span><strong>Map legend</strong><small>Recorded cases · {data?.year??2024}</small></span><ChevronDown size={17}/></button><div id="historical-legend-body" className="historical-capsule-body" hidden={openPanel!=='legend'}><h2>Recorded cases · {data?.year??2024}</h2><div><span><i className="historical-dot band-pale"/>Under 500</span><span><i className="historical-dot band-medium"/>500–999</span><span><i className="historical-dot band-strong"/>1,000+</span></div><p>Larger circle = more recorded cases. Size: 22 + √(cases ÷ 1,500) × 30 px.</p><p>Polygon risk levels: Low (under 25), Medium (25–49), High (50–74), Very high (75–100). Pale rose to crimson; Model estimates or time-only advisory rules, not a guarantee. Levels combine annual-volume predictions with assumed spatial/time/activity adjustments. For missing model inputs: 20:00–06:00 High, 06:00–10:00 Medium, 10:00–17:00 Low, 17:00–20:00 Medium. At 22:00–06:00, model Low becomes Medium and Medium becomes High; outer/lower-density references have a High minimum. Outer means over 20 km from the configured region centre; lower density means below the median of available supplied density values. These are assumed rules. Reference cells are not verified ward boundaries or current danger classifications.</p><small>Historical reporting, not current safety. Display bands only · not NCRB danger classifications. Approximate reference points; no danger radii.</small><Link className="historical-legend-method" to="/evidence">Crime data & sources <ArrowUpRight size={13}/></Link></div></Glass>
 <Glass className={`historical-filters historical-capsule ${openPanel==='filters'?'is-open':''}`} aria-label="Map filters"><button id="filters-toggle" className="historical-capsule-trigger" onClick={()=>toggle('filters')} aria-expanded={openPanel==='filters'} aria-controls="map-filters-body"><SlidersHorizontal size={18}/><span><strong>Help nearby</strong><small>{visibleKinds.length?'Help nearby & layout':'Help layers hidden'}</small></span><ChevronDown size={17}/></button><div id="map-filters-body" className="historical-capsule-body" hidden={openPanel!=='filters'}><label className="historical-filter-field">Map layout<select value={layout} onChange={e=>setLayout(e.target.value as BasemapLayout)}>{mapLayouts.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label><fieldset><legend>Help nearby · mapped OSM places</legend>{(['police','hospital','metro'] as const).map(kind=><label className="historical-filter-check" key={kind}><input type="checkbox" checked={visibleKinds.includes(kind)} onChange={e=>setVisibleKinds(list=>e.target.checked?[...list,kind]:list.filter(k=>k!==kind))}/><span>{{police:'Police stations',hospital:'Hospitals',metro:'Metro stations',bus:'Bus stops',fire:'Fire stations'}[kind]}</span><small>{help.filter(f=>f.properties.kind===kind).length}</small></label>)}</fieldset><p className="historical-small">Mapped facilities only; coverage and opening hours are not verified. If a category has no mapped records, it does not mean no facilities exist. Tap a marker for its source.</p><label className="historical-filter-field">Local time<select value={selectedHour??'now'} onChange={e=>setSelectedHour(e.target.value==='now'?null:Number(e.target.value))}><option value="now">Current time</option>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><p className="historical-small">Risk levels combine model estimates and time-based advisory rules, not a guarantee. Missing model inputs use a time-only advisory. Recorded totals remain unchanged.</p></div></Glass>
 </main>;
}
