import {historicalCopy} from '../lib/display-period';
import {lazy,Suspense} from 'react';
import NeighbourhoodSheet from './NeighbourhoodSheet';
import {X,ShieldCheck,Info} from 'lucide-react';
import type {City,RiskRecord} from '../types';
import {bands,getScore,displayLevel,riskColor} from '../lib/risk';
import {Button,Skeleton} from './ui';
const Charts=lazy(()=>import('./RiskCharts'));
export default function DetailPanel({record:r,city,band,setBand,day,crime,year,onClose,onHeightChange}:{record:RiskRecord;city?:City;band:number;setBand:(n:number)=>void;day:string;crime:string;year:string;onClose:()=>void;onHeightChange:(height:number)=>void}){const score=getScore(r,band,day,crime,year);const ranked=bands.map((name,i)=>({name,score:getScore(r,i,day,crime,year)})).filter((v):v is {name:string;score:number}=>v.score!==null).sort((a,b)=>b.score-a.score).slice(0,3);return <NeighbourhoodSheet name={r.name} onClose={onClose} onHeightChange={onHeightChange}><div className="detail-title"><p className="eyebrow">{r.provenance==='sample'?'SAMPLE CELL · NOT REAL DATA':'NEIGHBOURHOOD INSIGHT'}</p><Button size="icon" variant="ghost" aria-label="Close neighbourhood details" onClick={onClose}><X size={18}/></Button></div><h2>{r.name}</h2><p className="subheading">{city?.name} · {city?.state}</p><span className={`badge ${score!==null?'risk':''}`}><Info size={12}/>{displayLevel(score)}</span><div className="risk-stat"><div><strong className="stat-number">{score??'N/A'}<small> / 100</small></strong><p>{r.provenance==='sample'?'Illustrative score only':'Relative model estimate, not a guarantee'}</p></div><ShieldCheck size={32}/></div><div className="section-heading"><h3>Through the day</h3><span>{day}</span></div><div className="band-strip">{bands.map((b,i)=><button key={b} aria-label={b} aria-pressed={i===band} onClick={()=>setBand(i)}><i style={{background:riskColor(getScore(r,i,day,crime,year))}}/>{b.split('–')[0]}</button>)}</div><div className="detail-bento"><div><small>DATA CONFIDENCE</small>{r.confidence==='low'?'Limited data':`${r.confidence} confidence`}</div><div><small>PROVENANCE</small>{r.provenance==='sample'?'Synthetic sample':r.estimated?'Estimated allocation':'Observed source'}</div></div><div className="section-heading"><h3>Higher estimated windows</h3></div>{ranked.length?<ul>{ranked.map(w=><li key={w.name}>{w.name} · {w.score}/100 {r.provenance==='sample'?'(sample)':''}</li>)}</ul>:<p className="empty-copy">Time-specific estimates aren’t available.</p>}<Suspense fallback={<Skeleton/>}><Charts record={r}/></Suspense><div className="section-heading"><h3>Sources & evidence</h3></div>{r.sources.length?<ul>{r.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{historicalCopy(s.label)}</a></li>)}</ul>:<p className="empty-copy">{r.provenance==='sample'?'Generated test material. No real incidents, boundaries or risk observations.':'No admissible source records for this neighbourhood.'}</p>}<p className="page-footnote">Model estimate, not a guarantee. Not real-time. No area is risk-free.</p></NeighbourhoodSheet>}
