import {useEffect,useMemo,useRef,useState} from 'react';
import Map,{Marker,Source,Layer,Popup,AttributionControl,type MapRef,type MapLayerMouseEvent} from 'react-map-gl/maplibre';
import maplibregl,{type GeoJSONSource} from 'maplibre-gl';
import {useReducedMotion} from 'framer-motion';
import {circle} from '@turf/turf';
import {activityScenario,contextCells,currentPeriod,type LocalityContext,type Locality} from '../lib/locality-context';
import {Plus,Minus,LocateFixed} from 'lucide-react';
import {Button,Glass} from './ui';
import {detailedBasemap,type BasemapLayout} from '../lib/map-layouts';
import {addHelpIcons} from '../lib/help-icons';
import {contextScenario,mappedTransitNearby} from '../lib/context-scenario';
import {districtBand,districtDiameter,type HistoricalDistrict} from '../lib/historical-districts';
import type {Bounds,HelpFeature,UserPosition} from '../types';
import 'maplibre-gl/dist/maplibre-gl.css';

export default function HistoricalMapCanvas({districts,selectedId,theme,onSelect,bounds,center,openPanel,help,layout,scenario,timeBand,visibleKinds,caseCounts,context,userPosition,focusRequest,showContext}:{districts:HistoricalDistrict[];selectedId:string|null;theme:string;onSelect:(id:string)=>void;bounds:Bounds;center:{lat:number;lng:number};openPanel:'districts'|'details'|'legend'|'filters'|null;help:HelpFeature[];layout:BasemapLayout;scenario:boolean;timeBand:number;visibleKinds:HelpFeature['properties']['kind'][];caseCounts:(number|null)[];context:LocalityContext|null;userPosition:UserPosition|null;focusRequest:number;showContext:boolean}){
 const ref=useRef<MapRef>(null),reduce=useReducedMotion();const [ready,setReady]=useState(false),[error,setError]=useState('');
 const key=import.meta.env.VITE_MAPTILER_KEY??'';const style=useMemo(()=>detailedBasemap(theme,key,layout),[theme,key,layout]);
 useEffect(()=>setError(''),[style]);
 const [popup,setPopup]=useState<HelpFeature|null>(null);
 const [localPopup,setLocalPopup]=useState<Locality|null>(null);
 const focused=useRef(false),lastFocus=useRef(-1);
 useEffect(()=>{if(!userPosition){focused.current=false;return;}if(ready&&(!focused.current||lastFocus.current!==focusRequest)){ref.current?.flyTo({center:[userPosition.lng,userPosition.lat],zoom:14,duration:reduce?0:700});focused.current=true;lastFocus.current=focusRequest;}},[userPosition,focusRequest,ready,reduce]);
 const accuracy=useMemo(()=>userPosition?circle([userPosition.lng,userPosition.lat],Math.min(userPosition.accuracy,50000)/1000,{units:'kilometers',steps:48}):null,[userPosition]);
 const day=currentPeriod().day;
 const cells=useMemo(()=>contextCells(context?.records??[],timeBand,day),[context,timeBand,day]);
 useEffect(()=>{if(popup&&!visibleKinds.includes(popup.properties.kind))setPopup(null)},[visibleKinds,popup]);
 const activityByDistrict=useMemo(()=>new globalThis.Map(districts.map(d=>[d.id,mappedTransitNearby(d.reference.coordinates,help)])),[districts,help]);
 const helpPoints=useMemo(()=>({type:'FeatureCollection' as const,features:help.filter(f=>f.geometry.type==='Point'&&visibleKinds.includes(f.properties.kind))}),[help,visibleKinds]);
 const onHelpClick=async(e:MapLayerMouseEvent)=>{const f=e.features?.[0];if(!f)return;if(f.layer.id==='locality-context-fill'){setLocalPopup(context?.records.find(r=>r.id===f.properties?.id)??null);return;}if(f.layer.id==='ncr-help-clusters'){const src=ref.current?.getMap().getSource('ncr-help') as GeoJSONSource|undefined;if(!src)return;try{const zoom=await src.getClusterExpansionZoom(Number(f.properties?.cluster_id));ref.current?.easeTo({center:(f.geometry as GeoJSON.Point).coordinates as [number,number],zoom,duration:reduce?0:400})}catch{/* source can disappear during style change */}return;}const record=help.find(h=>h.properties.id===String(f.properties?.id));if(record)setPopup(record);};
 const padding=()=>window.innerWidth>760?{top:200,bottom:150,left:openPanel==='districts'?335:48,right:openPanel==='details'||openPanel==='filters'?365:48}:{top:180,bottom:openPanel==='details'||openPanel==='legend'?Math.min(window.innerHeight*.4+148,window.innerHeight-200):200,left:24,right:24};
 const recenter=()=>{ref.current?.fitBounds([[bounds.west,bounds.south],[bounds.east,bounds.north]],{padding:padding(),duration:reduce?0:700});};
 useEffect(()=>{const map=ref.current?.getMap();if(!map||!ready)return;const resize=()=>{map.resize();map.jumpTo({padding:padding()});};resize();const observer=new ResizeObserver(resize);observer.observe(map.getContainer());return()=>observer.disconnect();},[ready,openPanel]);
 useEffect(()=>{if(!ready)return;const record=districts.find(r=>r.id===selectedId);if(record)ref.current?.flyTo({center:record.reference.coordinates,zoom:11.8,padding:padding(),duration:reduce?0:650});},[selectedId,ready,reduce]);
 return <><Map ref={ref} mapLib={maplibregl} initialViewState={{longitude:center.lng,latitude:center.lat,zoom:10}} mapStyle={style} attributionControl={false} maxBounds={userPosition&&(userPosition.lng<bounds.west||userPosition.lng>bounds.east||userPosition.lat<bounds.south||userPosition.lat>bounds.north)?undefined:[bounds.west-.15,bounds.south-.15,bounds.east+.15,bounds.north+.15]} interactiveLayerIds={['ncr-help-clusters','ncr-help-points',...(showContext?['locality-context-fill']:[])]} onClick={onHelpClick} onStyleData={()=>{const map=ref.current?.getMap();if(map?.isStyleLoaded())addHelpIcons(map)}} onLoad={()=>{addHelpIcons(ref.current!.getMap());setReady(true);recenter();}} onError={()=>setError('Some base-map tiles could not load. District records remain available.')}>
 {showContext&&<Source id="locality-context" type="geojson" data={cells}><Layer id="locality-context-fill" type="fill" paint={{'fill-color':['case',['==',['get','score'],null],'#8a929c',['interpolate',['linear'],['get','score'],0,'#f7c5cf',50,'#d95774',100,'#9d183e']],'fill-opacity':.28,'fill-color-transition':{duration:350}}}/><Layer id="locality-context-outline" type="line" paint={{'line-color':'#b56679','line-width':.7,'line-opacity':.45}}/></Source>}
 {accuracy&&<Source id="gps-accuracy" type="geojson" data={accuracy}><Layer id="gps-accuracy-fill" type="fill" paint={{'fill-color':'#338aff','fill-opacity':.1}}/><Layer id="gps-accuracy-line" type="line" paint={{'line-color':'#338aff','line-width':1,'line-opacity':.5}}/></Source>}
 {userPosition&&<Marker latitude={userPosition.lat} longitude={userPosition.lng} anchor="center" style={{zIndex:5}}><span className="kaali-gps-dot" role="img" aria-label={`Device location; accuracy approximately ${Math.round(userPosition.accuracy)} metres`}/></Marker>}
 {showContext&&localPopup&&<Popup longitude={localPopup.coordinates[0]} latitude={localPopup.coordinates[1]} onClose={()=>setLocalPopup(null)}><div className="map-popup"><strong>{localPopup.name}</strong><p>Assumed activity index: {activityScenario(localPopup,timeBand,day,context?.records)??'Unknown'} / 100. Not a crime forecast.</p><p>Historical probes: {localPopup.traffic[day][timeBand]??'Unknown'} mean per segment-hour · Aug 2024.</p><p>Population: {localPopup.population??'Unknown'}; source density: {localPopup.density??'Unknown'} (year/units unverified).</p><small>Approximate reference cell, not locality boundaries. Local crime counts unknown.</small></div></Popup>}
 {districts.map(d=>{const diameter=districtDiameter(d.count);const estimate=scenario?contextScenario(d.count,caseCounts,(activityByDistrict.get(d.id)??0),timeBand):null;const band=scenario?(estimate===null?'unknown':estimate.score<35?'pale':estimate.score<70?'medium':'strong'):districtBand(d.count);return <Marker key={d.id} longitude={d.reference.coordinates[0]} latitude={d.reference.coordinates[1]} anchor="center" style={{zIndex:selectedId===d.id?2:1}}><button className={`historical-marker ${selectedId===d.id?'is-selected':''}`} aria-label={`${d.name} police district, ${d.count===null?'total missing':`${d.count} recorded cases`}, ${d.year}; approximate reference`} aria-pressed={selectedId===d.id} onClick={e=>{e.stopPropagation();onSelect(d.id);}} title={`${d.name} · ${d.count??'Not published'} cases · ${d.year}`}>
 <span className={`historical-circle band-${band}`} style={{width:diameter??24,height:diameter??24}} title={scenario?`${estimate?.score??'Unknown'} / 100 · assumed scenario, low confidence`:undefined}>{d.count===null?'?':d.count.toLocaleString('en-IN')}</span><span className="historical-marker-label">{d.name}</span></button></Marker>})}
 <Source id="ncr-help" type="geojson" data={helpPoints} cluster clusterMaxZoom={13} clusterRadius={40}><Layer id="ncr-help-clusters" type="symbol" filter={['has','point_count']} layout={{'icon-image':'kaali-icon-cluster','icon-size':1.7,'icon-allow-overlap':true,'text-field':['get','point_count_abbreviated'],'text-offset':[0,2.1],'text-size':11}} paint={{'text-color':theme==='dark'?'#ffffff':'#17313b','text-halo-color':theme==='dark'?'#17313b':'#ffffff','text-halo-width':1.5}}/><Layer id="ncr-help-points" type="symbol" filter={['!', ['has','point_count']]} layout={{'icon-image':['concat','kaali-icon-',['get','kind']],'icon-allow-overlap':false,'icon-size':1.2}}/><Layer id="ncr-help-names" type="symbol" minzoom={14} filter={['!', ['has','point_count']]} layout={{'text-field':['get','name'],'text-size':11,'text-offset':[0,1.7],'text-anchor':'top','text-max-width':12}} paint={{'text-color':theme==='dark'?'#f5f7fa':'#1c2634','text-halo-color':theme==='dark'?'#17202d':'#ffffff','text-halo-width':1.5}}/></Source>
 {popup&&popup.geometry.type==='Point'&&<Popup longitude={popup.geometry.coordinates[0]} latitude={popup.geometry.coordinates[1]} onClose={()=>setPopup(null)} closeOnClick={false}><div className="map-popup"><strong>{popup.properties.name}</strong><p>Mapped {popup.properties.kind} · availability not confirmed.</p><a href={popup.properties.source} target="_blank" rel="noreferrer">OpenStreetMap source ↗</a></div></Popup>}
 <AttributionControl position="bottom-right" compact={false} customAttribution="© MapTiler © OpenStreetMap contributors"/>
 </Map>{key&&<a className="historical-maptiler-logo" href="https://www.maptiler.com/" target="_blank" rel="noreferrer"><img src="https://api.maptiler.com/resources/logo.svg" alt="MapTiler" width="85" height="25"/></a>}<Glass className="historical-map-controls"><Button size="icon" variant="ghost" aria-label="Zoom in" onClick={()=>ref.current?.zoomIn({duration:reduce?0:250})}><Plus size={18}/></Button><Button size="icon" variant="ghost" aria-label="Zoom out" onClick={()=>ref.current?.zoomOut({duration:reduce?0:250})}><Minus size={18}/></Button><Button size="icon" variant="ghost" aria-label="Recenter on Delhi NCR" onClick={recenter}><LocateFixed size={18}/></Button></Glass>{(!key||error)&&<p className="historical-tile-note glass" role="status">{!key?'Configure MapTiler to show the street basemap. Circles use geographic reference coordinates.':error}</p>}</>;
}
