import {useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {LocateFixed,Share2,X} from 'lucide-react';
import {distance,point} from '@turf/turf';
import {Button,Glass,Sheet} from './ui';
import {locationSession} from '../lib/location-session';
import {currentPeriod,nearestReference,type LocalityContext} from '../lib/locality-context';
import type {UserPosition,HelpFeature} from '../types';
import {advisoryLevel,referenceAdvisory,localHour,precaution} from '../lib/advisory-risk';
import {mlIndex,type MLVolume} from '../lib/ml-volume';
import {generateLocalAdvice,type AIContext} from '../lib/ai-advice';
export default function LocalAwareness({context,help,user,onPosition,onLocate,ml,center,timezone}:{center:{lat:number;lng:number};timezone:string;context:LocalityContext|null;help:HelpFeature[];user:UserPosition|null;onPosition:(u:UserPosition|null)=>void;onLocate:()=>void;regional:{year:number;count:number|null}|null;ml:MLVolume|null}){
 const [consent,setConsent]=useState(false),[enabled,setEnabled]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(new Date());
 const [ai,setAI]=useState(''),[aiBusy,setAIBusy]=useState(false);const aiAbort=useRef<AbortController|null>(null);
 const session=useRef<ReturnType<typeof locationSession>|null>(null);
 useEffect(()=>{if(!navigator.geolocation)return;let mounted=true;session.current=locationSession(navigator.geolocation,onPosition,()=>{setEnabled(false);setError('Location was unavailable. You can still explore the map manually.');},{enableHighAccuracy:true,maximumAge:5000,timeout:20000});if(navigator.permissions)navigator.permissions.query({name:'geolocation'}).then(permission=>{if(mounted&&permission.state==='granted'){setEnabled(true);session.current?.start();}}).catch(()=>{});return()=>{mounted=false;session.current?.stop()}},[onPosition]);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[]);
 const nearest=useMemo(()=>user&&context?nearestReference(user,context.records):null,[user,context]);
 const police=useMemo(()=>{if(!user)return null;return help.filter(f=>f.properties.kind==='police'&&f.geometry.type==='Point').map(f=>({name:f.properties.name,km:distance(point([user.lng,user.lat]),point(f.geometry.coordinates as [number,number]),{units:'kilometers'})})).sort((a,b)=>a.km-b.km)[0]??null},[help,user]);
 const period=currentPeriod(now),r=nearest?.record,probes=r?.traffic[period.day][period.band];
 const index=r?mlIndex(ml,r,period.band,period.day,context?.records??[]):null;
 const hour=localHour(now,timezone),level=r?referenceAdvisory(ml,r,period.band,period.day,hour,context?.records??[],center):advisoryLevel(null,hour);
 useEffect(()=>{aiAbort.current?.abort();setAI('');setAIBusy(false);return()=>aiAbort.current?.abort()},[enabled,user!==null,r?.id,period.band,period.day,index,level]);
 const requestAI=async()=>{aiAbort.current?.abort();const controller=new AbortController();aiAbort.current=controller;setAIBusy(true);setError('');const anonymous:AIContext={index:level==='Low'?'lower':level==='Medium'?'middle':'higher',time:period.band===0||period.band===5?'night':'day',activity:probes===null||probes===undefined?'unknown':probes<2?'lower':'higher',population:r?.population===null||!r?'unknown':'available'};try{const text=await generateLocalAdvice(anonymous,controller.signal);if(!controller.signal.aborted)setAI(text)}catch{if(!controller.signal.aborted)setError('Start the local AI advice service with an installed Ollama model. The on-device summary remains available.')}finally{if(!controller.signal.aborted)setAIBusy(false)}};
 const share=async()=>{if(!user)return;try{if(!navigator.share){setError('Use your device’s location-sharing app; native sharing is unavailable here.');return;}await navigator.share({title:'My current location',text:`My device location (approximately ±${Math.round(user.accuracy)} m): https://www.openstreetmap.org/?mlat=${user.lat}&mlon=${user.lng}#map=17/${user.lat}/${user.lng}`});}catch{setError('Location sharing was cancelled or unavailable.')}};
 return <><Button className="historical-locate-button glass" size="icon" variant="ghost" aria-label="Locate me" onClick={()=>enabled?onLocate():setConsent(true)}><LocateFixed size={20}/></Button><Sheet open={consent} onOpenChange={setConsent} title="Your location, on this device"><p>Show your device’s reported position and an awareness summary. Coordinates stay in memory here and are cleared when you stop. We do not send GPS to a geocoder or AI service. Map tiles reveal the viewed area to the map provider.</p><p>The blue dot is your device’s estimate; its accuracy circle is not a guarantee of an exact position.</p><Button onClick={()=>{setConsent(false);setError('');if(!session.current){setError('Location is unavailable in this browser.');return;}setEnabled(true);session.current.start();}}>Allow location</Button><Button variant="ghost" onClick={()=>setConsent(false)}>Continue without location</Button></Sheet>
 {enabled&&<Glass className="historical-location-card" aria-label="On-device location awareness"><div className="location-card-heading"><strong>{user?'Your surroundings':'Finding your location…'}</strong><Button size="icon" variant="ghost" aria-label="Stop location and clear position" onClick={()=>{session.current?.stop();setEnabled(false)}}><X size={18}/></Button></div>{user&&<><div className={`location-risk-badge risk-${level.toLowerCase().replace(' ','-')}`}>{level} · advisory level</div>{r&&<p className="location-reference-name">Near {r.name}</p>}<p className="location-advice-copy">{precaution(level)}</p><p className="historical-small">Model estimate with time-based advisory rules; not a guarantee of safety.</p><small>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,hour:'numeric',minute:'2-digit'}).format(now)} IST · GPS accuracy ±{Math.round(user.accuracy)} m</small>{r&&<details><summary>How this advice is formed</summary><p>Level combines model output with assumed local-time rules. Without a model index, it uses time only. No measured neighbourhood risk is inferred.</p><p>Nearest supplied reference: {r.name}, {nearest!.km.toFixed(2)} km away. Names/coordinates are unverified; this is not an exact locality match.</p><p>Historical sampled road probes: {probes===null||probes===undefined?'unavailable':`${probes.toFixed(2)} mean per segment-hour`} ({context?.trafficPeriod}); not live traffic or people counts.</p><p>Population: {r.population?.toLocaleString('en-IN')??'unknown'}. Source density: {r.density?.toLocaleString('en-IN')??'unknown'}; year/units unverified. Local recorded crime total and calibrated safety risk: unknown.</p></details>}{police&&<p className="historical-small">Nearest mapped police reference: {police.name} · {police.km.toFixed(1)} km straight-line; availability unconfirmed.</p>}<div className="location-card-actions"><a href="tel:112">Call 112</a><Button size="small" variant="ghost" onClick={share}><Share2 size={16}/>Share location</Button><Link to="/helplines">Helplines</Link></div><Button size="small" variant="secondary" disabled={aiBusy} onClick={requestAI}>{aiBusy?'Generating locally…':'Generate AI advice locally'}</Button><p className="historical-small">Sends only anonymous categories to a local Ollama service: no GPS, locality name, case totals or personal identifiers. No cloud service or tracking.</p>{ai&&<p className="ai-advice-text" role="status">{ai} This is advice only—stay aware of your surroundings and take care.</p>}<small>The initial summary uses on-device rules. AI wording is generated only after the button is pressed.</small></>}</Glass>}{error&&<Glass className="historical-location-error" role="status">{error}<Button variant="ghost" size="small" onClick={()=>setError('')}>Dismiss</Button></Glass>}</>;
}
