import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {motion} from 'framer-motion';
import {Navigation,ShieldCheck,Share2,Phone,X} from 'lucide-react';
import {booleanPointInPolygon,point} from '@turf/turf';
import type {Region,RiskRecord,HelpFeature,UserPosition} from '../types';
import {neighbourhoodAt,nearestPolice} from '../lib/geo';
import {timeContext,getScore,bands,displayLevel} from '../lib/risk';
import {Button,Glass,Sheet} from './ui';
export default function LocationControl({region,regions,onRegion,records,onJurisdiction,onFocus,onSelect,lang,onMessage,helpFeatures,onPosition}:{region:Region;regions:Region[];onRegion:(id:string)=>void;records:RiskRecord[];onJurisdiction:(id:string)=>void;onFocus:(p:{lat:number;lng:number})=>void;onSelect:(r:RiskRecord)=>void;lang:string;onMessage:(s:string)=>void;helpFeatures:HelpFeature[];onPosition:(p:UserPosition|null)=>void}){const[consent,setConsent]=useState(false),[position,setPosition]=useState<UserPosition|null>(null),[locating,setLocating]=useState(false),[status,setStatus]=useState(''),[visible,setVisible]=useState(false),[clock,setClock]=useState(new Date());const latest=useRef({regions,region,records,onSelect});latest.current={regions,region,records,onSelect};const watch=useRef<number|null>(null),boundaries=useRef(new Map<string,GeoJSON.FeatureCollection>());useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),60000);return()=>{clearInterval(timer);if(watch.current!==null)navigator.geolocation.clearWatch(watch.current)}},[]);useEffect(()=>{for(const r of regions)if(r.boundaryFile&&!boundaries.current.has(r.id))fetch(r.boundaryFile).then(x=>x.json()).then(x=>boundaries.current.set(r.id,x)).catch(()=>{});},[regions]);const neighbourhood=position?neighbourhoodAt(records,position):null;const city=region.cities.find(c=>c.id===neighbourhood?.cityId);const current=timeContext(region.timezone,clock);const score=neighbourhood?getScore(neighbourhood,current.band,current.day):null;const next=neighbourhood&&score!==null?Array.from({length:5},(_,i)=>(current.band+i+1)%6).find(b=>(getScore(neighbourhood,b,current.day)??-1)>score):undefined;const police=position&&city?nearestPolice(helpFeatures,position,city.id):null;useEffect(()=>{onJurisdiction(city?.helplineSet??'national')},[city,onJurisdiction]);
 const stop=()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setPosition(null);onPosition(null);setVisible(false);setLocating(false);onJurisdiction('national')};
 const start=()=>{setConsent(false);if(!navigator.geolocation){onMessage('Location is unavailable in this browser. Search for a locality instead.');return;}if(watch.current!==null){if(position)onFocus(position);setVisible(true);return;}setLocating(true);watch.current=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy};setPosition(p);onPosition(p);setLocating(false);setVisible(true);onFocus(p);let matched:Region|undefined;for(const r of latest.current.regions){const boundary=boundaries.current.get(r.id);if(boundary?.features.some(f=>(f.geometry.type==='Polygon'||f.geometry.type==='MultiPolygon')&&booleanPointInPolygon(point([p.lng,p.lat]),f as GeoJSON.Feature<GeoJSON.Polygon|GeoJSON.MultiPolygon>)))matched=r;}if(matched){if(matched.id!==latest.current.region.id)onRegion(matched.id);setStatus('')}else{const inViewport=latest.current.regions.some(r=>p.lat<=r.bounds.north&&p.lat>=r.bounds.south&&p.lng>=r.bounds.west&&p.lng<=r.bounds.east);setStatus(inViewport?'Verified boundaries are not available here yet. We cannot confirm your neighbourhood or jurisdiction.':"We don’t cover your area yet. Helplines are still available.")}const n=neighbourhoodAt(latest.current.records,p);if(n)latest.current.onSelect(n);},()=>{setLocating(false);onMessage('Location was unavailable or denied. You can search for a locality instead.');if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;},{enableHighAccuracy:false,maximumAge:15000,timeout:12000});};
 const share=async()=>{if(!position)return;const url=`https://www.openstreetmap.org/?mlat=${position.lat}&mlon=${position.lng}#map=16/${position.lat}/${position.lng}`;try{if(navigator.share)await navigator.share({title:'My current location',text:'My current location, shared from Aegis.',url});else onMessage('Native sharing is unavailable in this browser. Use your device’s location sharing app.')}catch(e){if((e as Error).name!=='AbortError')onMessage('Sharing could not be opened.')}};
 const card=<motion.div className="glass location-card" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div className="detail-title"><p className="eyebrow"><ShieldCheck size={14}/>YOUR SURROUNDINGS</p><Button variant="ghost" size="icon" aria-label="Hide location card" onClick={()=>setVisible(false)}><X size={16}/></Button></div><h2>{city&&neighbourhood?`${lang==='hi'?'आप यहाँ हैं':'You’re in'} ${neighbourhood.name}, ${city.name}.`:lang==='hi'?'आपकी जगह, आपकी निजता।':'Your location. Your privacy.'}</h2><span className="badge">{displayLevel(score)}</span><p>{status||`${next!==undefined?`Next higher estimated window: ${bands[next]}. `:''}${lang==='hi'?'मुख्य और रोशनी वाली सड़कों का विकल्प रखें। ज़रूरत पड़ने पर 112 पर कॉल करें।':score!==null&&score>=50?'Consider well-lit main roads, and share your plans with someone you trust. Keep 112 handy.':'Stay aware of your surroundings, keep a trusted contact handy, and choose a route that feels comfortable.'}`}</p>{police&&<p>Nearest mapped police station: {police.feature.properties.name} · {police.km.toFixed(1)} km straight-line distance.</p>}<p>{lang==='hi'?'यात्रियों के लिए: लाइसेंस प्राप्त टैक्सी चुनें और अपनी यात्रा की जानकारी साझा करें।':'Visitor tip: choose licensed cabs and well-lit routes. Check your pickup point before travelling.'}</p><div className="location-actions"><Button asChild><a href="tel:112"><Phone size={14}/>Call 112</a></Button><Button variant="secondary" onClick={share}><Share2 size={14}/>Share location</Button><Button variant="help" asChild><a href="/helplines">Helplines</a></Button></div>{status.includes('cover')&&<a className="text-link" href="/about#suggest">Suggest a city</a>}<button className="text-link" onClick={stop}>Turn location off & clear</button></motion.div>;
 return <><Glass><Button variant="ghost" onClick={()=>position?start():setConsent(true)} aria-label="Locate me" disabled={locating}><Navigation size={18}/><span className="action-label">{locating?'Locating…':lang==='hi'?'मेरी जगह':'Locate me'}</span></Button></Glass><Sheet open={consent} onOpenChange={setConsent} title={lang==='hi'?'अपनी जगह जानें':'A little context, just for you'}><p>{lang==='hi'?'आपकी अनुमति से, आपकी जगह का मिलान इसी डिवाइस पर होगा।':'With your permission, Aegis matches your location to neighbourhood boundaries on this device. Coordinates are never stored or sent to our servers.'}</p><p>Map providers receive the map viewport when tiles load. Your exact GPS coordinates are not sent to the geocoder. Sharing sends your location only when you choose “Share location”.</p><div className="sheet-actions"><Button onClick={start}>{lang==='hi'?'स्थान की अनुमति दें':'Allow location'}</Button><Button variant="ghost" onClick={()=>setConsent(false)}>Use search instead</Button></div></Sheet>{visible&&position&&document.getElementById('main')&&createPortal(card,document.getElementById('main')!)}</>;
}

