import {lazy,Suspense,useCallback,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Search,Navigation,Layers,Info,ArrowUpRight,ShieldCheck,ChevronRight,MapPin,Moon,Sun,SlidersHorizontal,HeartHandshake,Building2,TrainFront,Bus,Hospital,Lightbulb,X} from 'lucide-react';
import {motion} from 'framer-motion';
import type {Region,RiskRecord,HelpFeature} from '../types';
import {bands,loadRisk,getScore,riskColor,displayLevel,timeContext,contains} from '../lib/risk';
import {Button,Glass,Chip,Sheet,Toast,Skeleton} from './ui';
import DetailPanel from './DetailPanel';
import MapBoundary from './MapBoundary';
import PlaceSearch from './PlaceSearch';
import LocationControl from './LocationControl';
const MapView=lazy(()=>import('./MapView'));
type Props={region:Region;regions:Region[];onRegion:(id:string)=>void;theme:string;lang:string;onJurisdiction:(id:string)=>void};
export default function MapPage({region,regions,onRegion,theme,lang,onJurisdiction}:Props){
 const [records,setRecords]=useState<RiskRecord[]>([]),[sample,setSample]=useState(false),[band,setBand]=useState(()=>timeContext(region.timezone).band),[day,setDay]=useState(()=>timeContext(region.timezone).day),[city,setCity]=useState('all'),[selected,setSelected]=useState<RiskRecord|null>(null),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[filters,setFilters]=useState(false),[crime,setCrime]=useState('all'),[year,setYear]=useState('all'),[help,setHelp]=useState(false),[helpFeatures,setHelpFeatures]=useState<HelpFeature[]>([]),[layers,setLayers]=useState<string[]>([]),[focus,setFocus]=useState<{lat:number;lng:number}|null>(null),[mapFailed,setMapFailed]=useState(false),[detailHeight,setDetailHeight]=useState(0),[userPosition,setUserPosition]=useState<import('../types').UserPosition|null>(null);
 const [params]=useSearchParams();
 useEffect(()=>{if(params.get('help')==='1')setHelp(true)},[params]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setRecords([]);setSelected(null);fetch(sample?region.sampleFile:region.neighbourhoodFile,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Neighbourhood data could not be loaded.');return r.json()}).then(loadRisk).then(setRecords).catch(e=>{if(e.name!=='AbortError')setMessage(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[sample,region]);
 useEffect(()=>{setCity('all');setFocus(null);setSearch('');const controller=new AbortController();fetch(region.helpFile,{signal:controller.signal}).then(r=>r.json()).then(x=>setHelpFeatures(x.features??[])).catch(()=>setHelpFeatures([]));return()=>controller.abort()},[region]);
 const locationRecords=useMemo(()=>records.filter(r=>r.provenance!=='sample'),[records]);
 const clearLocation=useCallback(()=>{setSelected(null);setFocus(null)},[]);
 const filtered=useMemo(()=>records.filter(r=>(city==='all'||r.cityId===city)&&r.name.toLowerCase().includes(search.toLowerCase())),[records,city,search]);
 const configured=!mapFailed;
 const mapFailure=useCallback(()=>{setMapFailed(true);setMessage('The interactive map is unavailable. A labelled overview is shown; details and helplines still work.')},[]);
 const onSelect=useCallback((r:RiskRecord)=>{setSelected(r);setHelp(false);const p=r.geometry.type==='Polygon'?r.geometry.coordinates[0]:r.geometry.coordinates[0][0];setFocus({lat:p.reduce((s,v)=>s+v[1],0)/p.length,lng:p.reduce((s,v)=>s+v[0],0)/p.length})},[]);
 const onPlace=useCallback((p:{lat:number;lng:number})=>{setFocus(p);const r=records.find(r=>r.boundaryStatus==='verified'&&contains(r,p.lng,p.lat));setSelected(r??null);if(!r)setMessage('No verified neighbourhood coverage at this address. Helplines are still available.')},[records]);
 const cityInfo=region.cities.find(c=>c.id===city);
 const years=[...new Set(records.map(r=>r.year).filter((y):y is number=>y!==null))];
 const coverage=cityInfo?.coverage??Math.round(region.cities.reduce((s,c)=>s+c.coverage,0)/region.cities.length);
 return <main id="main" className={`explore ${sample?'sample-mode':''} ${selected?'has-details':''}`}>
 <div className="map-canvas">{configured?<MapBoundary key={region.id} onFailure={mapFailure} fallback={null}><Suspense fallback={<div className="map-status"><Skeleton/></div>}><MapView key={`${region.id}-${sample}`} region={region} theme={theme} layers={{records:filtered,help:helpFeatures.filter(f=>layers.includes(f.properties.kind)&&(city==='all'||f.properties.cityId===city)),sample}} timeBand={band} day={day} crime={crime} year={year} city={city} selectedId={selected?.id??null} focus={focus} userPosition={userPosition} detailHeight={detailHeight} onFatalError={mapFailure} onSelect={onSelect} onError={setMessage}/></Suspense></MapBoundary>:<MapFallback region={region} records={filtered} band={band} day={day} crime={crime} year={year} onSelect={onSelect}/>}</div>
 <div className="map-toolbar"><PlaceSearch region={region} onSelect={onPlace}/><Glass className="cities-toolbar"><Chip active={city==='all'} onClick={()=>{setCity('all');setSelected(null);setFocus(null)}}>{`All ${region.name}`}</Chip>{region.cities.map(c=><Chip key={c.id} active={city===c.id} onClick={()=>{setCity(c.id);setSelected(null);setFocus(null)}}>{c.name}</Chip>)}</Glass></div>
 <Glass className="overview aurora"><p className="eyebrow"><span className="status-dot"/>{sample?'ILLUSTRATIVE PREVIEW':`${region.name} · EARLY ACCESS`}</p><h1>{lang==='hi'?<>अपने इलाके<br/>को जानें।</>:<>A little more<br/>aware.</>}</h1><p className="intro">{lang==='hi'?'बेहतर जानकारी, सोच-समझकर फैसले।':'Understand your surroundings. Make informed choices, wherever you go.'}</p><div className="risk-preview-control"><Button variant="secondary" aria-pressed={sample} onClick={()=>{setSample(!sample);setSelected(null);setSearch('');setCrime('all');setYear('all')}}>{sample?'Exit sample red zones':'Preview red zones · sample'}</Button><p>{sample?'Synthetic scores only. Move the time slider and select a cell to explore.':'Real red-zone predictions await neighbourhood observations and model validation.'}</p></div><div className="overview-stat"><div><strong className="stat-number">{coverage}<span style={{fontSize:16}}>%</span></strong><small>verified neighbourhood coverage</small></div><ShieldCheck size={27}/></div><span className="badge"><Info size={12}/> Limited data · not a measure of safety</span><div className="section-heading"><h2>{sample?'Explore sample cells':'Coverage by city'}</h2><span>{sample?filtered.length:region.cities.length} {sample?'cells':'cities'}</span></div>{loading?<Skeleton/>:<div className="zone-list">{sample?filtered.map(r=><button className="zone-row" key={r.id} onClick={()=>onSelect(r)}><span className="zone-symbol" style={{background:riskColor(getScore(r,band,day,crime,year)),color:'#202431'}}>{getScore(r,band,day,crime,year)??'?'}</span><span><strong>{r.name}</strong><small>Sample · {displayLevel(getScore(r,band,day,crime,year))}</small></span><ChevronRight size={15}/></button>):region.cities.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><button className="zone-row" key={c.id} onClick={()=>{setCity(c.id);setMessage(`${c.name}: ${c.coverage}% verified coverage. No supported neighbourhood estimates yet.`)}}><span className="zone-symbol"><MapPin size={14}/></span><span><strong>{c.name}</strong><small>Limited data · {c.coverage}% coverage</small></span><ChevronRight size={15}/></button>)}{sample&&!filtered.length&&<p className="empty-copy">No matching neighbourhoods. Try another search or city.</p>}</div>}<label className="sample-switch"><input type="checkbox" checked={sample} onChange={e=>{setSample(e.target.checked);setSelected(null);setSearch('')}}/> Explore sample data</label><div className="overview-note"><Info size={14}/><span>Missing data never means lower risk. <a className="text-link" href="/about">How we use evidence <ArrowUpRight size={12}/></a></span></div></Glass>
 {configured&&!import.meta.env.VITE_MAPTILER_KEY&&!sample&&<div className="map-status"><div className="status-icon"><Layers size={25}/></div><h2>The picture is still coming together.</h2><p>Verified neighbourhood estimates aren’t available yet. Explore the sample experience or find a helpline.</p><small>MapTiler setup required · no basemap key configured</small></div>}
 {!configured&&<Glass className="renderer-fallback"><Info size={16}/><span>Geometry overview · street map unavailable</span><Button variant="secondary" size="small" onClick={()=>setMapFailed(false)}>Retry map</Button></Glass>}
 {sample&&<div className="sample-banner"><Info size={16}/><span>Sample cells, scores and charts. Illustrative only—not real neighbourhood risk.</span></div>}
 <Glass className="legend"><h2>{sample?'Sample risk scale':'Estimated risk'}</h2><div className="legend-levels">{['Lower','Moderate','High','Very high'].map((x,i)=><div className="legend-level" key={x}><i style={{background:`var(--risk-${i+1})`,backgroundImage:i>1?'repeating-linear-gradient(45deg,transparent 0 3px,#ffffff40 3px 4px)':undefined}}/><small>{i+1} · {x}</small></div>)}</div><p><span className="legend-unknown"/>Insufficient data ≠ lower risk</p></Glass>
 <Glass className="time-control"><div className="time-control-top"><span>{lang==='hi'?'समय के अनुसार देखें':'Explore by time'} <span className="muted">· {day==='weekday'?'Weekday':'Weekend'}</span></span><strong>{bands[band]}</strong></div><div className="time-slider"><Moon size={17}/><input type="range" min="0" max="5" step="1" value={band} aria-label="Time of day" aria-valuetext={`${bands[band]} ${region.timezone}`} onChange={e=>setBand(Number(e.target.value))}/><Sun size={17}/></div><div className="time-ticks">{['00','04','08','12','16','20'].map(t=><span key={t}>{t}</span>)}</div></Glass>
 <div className="map-actions"><Glass><Button variant="ghost" onClick={()=>setFilters(true)} aria-label="Filter risk estimates"><SlidersHorizontal size={18}/><span className="action-label">Filters</span></Button></Glass><Glass><Button variant="help" aria-label="Help nearby" onClick={()=>setHelp(true)}><HeartHandshake size={18}/><span className="action-label">Help nearby</span></Button></Glass><LocationControl region={region} regions={regions} onRegion={onRegion} records={locationRecords} onClear={clearLocation} onJurisdiction={onJurisdiction} onFocus={setFocus} onSelect={onSelect} lang={lang} onMessage={setMessage} helpFeatures={helpFeatures} onPosition={setUserPosition}/></div>
 <div className="map-credit">{sample?'Sample geometry · ':'Model estimate, not a guarantee · '}Awareness only · Not real-time{!configured?' · Schematic view, not a basemap':''}</div>
 {selected&&<DetailPanel record={selected} city={region.cities.find(c=>c.id===selected.cityId)} band={band} setBand={setBand} day={day} crime={crime} year={year} onClose={()=>setSelected(null)} onHeightChange={setDetailHeight}/>}
 <Sheet open={filters} onOpenChange={setFilters} title="Your view, your context"><p>Choose a reporting period and category. Unsupported combinations show insufficient data.</p><div className="filters"><label>Day type<select value={day} onChange={e=>setDay(e.target.value)}><option value="weekday">Weekday</option><option value="weekend">Weekend</option></select></label><label>Crime type<select value={crime} onChange={e=>setCrime(e.target.value)}><option value="all">All categories</option><option value="harassment">Harassment</option><option value="sexual-assault">Sexual assault</option><option value="rape">Rape</option><option value="trafficking">Trafficking</option></select></label><label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option value="all">Latest available</option>{years.map(y=><option key={y}>{y}</option>)}</select></label></div><div className="sheet-actions"><Button onClick={()=>setFilters(false)}>Apply filters</Button><Button variant="ghost" onClick={()=>{setCrime('all');setYear('all');setDay('weekday')}}>Reset</Button></div></Sheet>
 <Sheet open={help} onOpenChange={setHelp} title="A little help nearby"><p>OpenStreetMap services, not field-verified. Some may be missing or out of date. City filtering requires verified jurisdiction boundaries.</p><div className="help-list">{[{id:'police',name:'Police stations',icon:Building2},{id:'hospital',name:'Hospitals',icon:Hospital},{id:'metro',name:'Metro stations',icon:TrainFront},{id:'bus',name:'Bus stops',icon:Bus},{id:'road',name:'OSM lit=yes main roads',icon:Lightbulb}].map(x=><label className="help-row" key={x.id}><x.icon size={21}/><span style={{flex:1}}><strong>{x.name}</strong><p>{helpFeatures.filter(f=>f.properties.kind===x.id).length||'No'} mapped {x.id==='road'?'segments':'locations'} loaded</p></span><input type="checkbox" aria-label={`Show ${x.name}`} checked={layers.includes(x.id)} onChange={e=>setLayers(e.target.checked?[...layers,x.id]:layers.filter(i=>i!==x.id))}/></label>)}</div><div className="sheet-actions"><Button asChild variant="help"><a href="/helplines">Open helplines <ArrowUpRight size={15}/></a></Button><Button onClick={()=>setHelp(false)}>Done</Button></div></Sheet>
 {message&&<Toast onClose={()=>setMessage('')}>{message}</Toast>}
 </main>
}
function MapFallback({region,records,band,day,crime,year,onSelect}:{region:Region;records:RiskRecord[];band:number;day:string;crime:string;year:string;onSelect:(r:RiskRecord)=>void}){const b=region.bounds;const project=([lng,lat]:number[])=>[(lng-b.west)/(b.east-b.west)*1200,(b.north-lat)/(b.north-b.south)*800];return <div className="map-fallback"><div className="schematic-grid"/>{region.cities.map(c=><span key={c.id} className="schematic-label" style={{left:`${project([c.center.lng,c.center.lat])[0]/12}%`,top:`${project([c.center.lng,c.center.lat])[1]/8}%`}}>{c.name.toUpperCase()}</span>)}<svg viewBox="0 0 1200 800" role="img" aria-label="Neighbourhood geometry overview. Not a street map."><defs><pattern id="risk-hatch" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line y2="8" stroke="white" strokeOpacity=".3"/></pattern></defs>{records.map(r=>{const ring=r.geometry.type==='Polygon'?r.geometry.coordinates[0]:r.geometry.coordinates[0][0];const points=ring.map(p=>project(p).join(',')).join(' ');const score=getScore(r,band,day,crime,year);return <g key={r.id}><polygon className="sample-polygon" points={points} fill={riskColor(score)} fillOpacity=".75" tabIndex={0} role="button" aria-label={`${r.name}: ${displayLevel(score)}. ${r.provenance==='sample'?'Sample data.':'Model estimate, not a guarantee.'}`} onClick={()=>onSelect(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(r)}}}><title>{r.name} · {displayLevel(score)} {r.provenance==='sample'?' · sample':''}</title></polygon>{score!==null&&score>=50&&<polygon points={points} fill="url(#risk-hatch)" pointerEvents="none"/>}</g>})}</svg></div>}


