import {displayPeriod} from '../lib/display-period';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Map,{type MapRef,Popup,Marker,Source,Layer,AttributionControl,type MapLayerMouseEvent} from 'react-map-gl/maplibre';
import maplibregl,{type GeoJSONSource, type Map as GLMap} from 'maplibre-gl';
import {Protocol} from 'pmtiles';
import {circle} from '@turf/turf';
import {useReducedMotion} from 'framer-motion';
import {Plus,Minus,Compass,Box,Layers2,MapPin} from 'lucide-react';
import {Button,Glass} from './ui';
import type {Region,RiskRecord,HelpFeature,UserPosition} from '../types';
import {baseStyle,restoreRisk,featureTarget,selectFeature,applyScores,filterRisk,riskSource} from '../lib/map-state';
import {getScore,displayLevel} from '../lib/risk';
import {addHelpIcons} from '../lib/help-icons';
import {mapPadding} from '../lib/map-layout';
import type {DistrictPoints} from '../lib/district-points';
import 'maplibre-gl/dist/maplibre-gl.css';
const protocol=new Protocol();maplibregl.addProtocol('pmtiles',protocol.tile);
export type MapViewProps={region:Region;layers:{records:RiskRecord[];help:HelpFeature[];sample:boolean};selectedId:string|null;timeBand:number;theme:string;day:string;crime:string;year:string;city:string;focus:{lat:number;lng:number}|null;userPosition:UserPosition|null;detailHeight:number;onFatalError:()=>void;onSelect:(r:RiskRecord)=>void;onError:(message:string)=>void;districtPoints?:DistrictPoints;onDistrictSelect?:(id:string)=>void};
export default function MapView(p:MapViewProps){const ref=useRef<MapRef>(null),previous=useRef<string|null>(null),hoverId=useRef<string|null>(null),latest=useRef(p);latest.current=p;const reduce=useReducedMotion();const [ready,setReady]=useState(false),[threeD,setThreeD]=useState(false),[popup,setPopup]=useState<{lat:number;lng:number;text:string;source?:string}|null>(null);const key=import.meta.env.VITE_MAPTILER_KEY??'';const style=useMemo(()=>baseStyle(p.theme,key),[p.theme,key]);const interactive=['kaali-fill','kaali-3d','help-clusters','help-points'];
 const sync=useCallback((map:GLMap)=>{const a=latest.current;addHelpIcons(map);restoreRisk(map,a.region,a.layers.records,a.layers.sample);filterRisk(map,a.layers.records);applyScores(map,a.region,a.layers.records,a.layers.sample,a.timeBand,a.day,a.crime,a.year);selectFeature(map,a.region,a.layers.sample,null,a.selectedId);previous.current=a.selectedId;},[]);
 const onLoad=useCallback(()=>{const map=ref.current!.getMap();sync(map);map.on('style.load',()=>sync(map));setReady(true)},[sync]);
 useEffect(()=>{const map=ref.current?.getMap();if(!ready||!map||!map.isStyleLoaded())return;const src=map.getSource(riskSource);if(src?.type==='geojson')(src as GeoJSONSource).setData({type:'FeatureCollection',features:p.layers.records.map(r=>({type:'Feature',id:r.id,geometry:r.geometry,properties:{id:r.id,name:r.name}}))});sync(map)},[p.layers.records,p.layers.sample,ready,sync]);
 useEffect(()=>{const map=ref.current?.getMap();if(!ready||!map?.getSource(riskSource))return;let frame=0;const start=performance.now();const initial=new globalThis.Map(p.layers.records.map(r=>[r.id,Number(map.getFeatureState(featureTarget(r.id,p.region,p.layers.sample)).score??0)]));const update=(now:number)=>{if(!map.isStyleLoaded()||!map.getSource(riskSource))return;const t=reduce?1:Math.min((now-start)/260,1);for(const r of p.layers.records){const score=getScore(r,p.timeBand,p.day,p.crime,p.year);map.setFeatureState(featureTarget(r.id,p.region,p.layers.sample),{known:score!==null,score:(initial.get(r.id)??0)+( (score??0)-(initial.get(r.id)??0))*t})}if(t<1)frame=requestAnimationFrame(update)};frame=requestAnimationFrame(update);return()=>cancelAnimationFrame(frame)},[ready,p.timeBand,p.day,p.crime,p.year,p.layers.records,p.region,p.layers.sample,reduce]);
 useEffect(()=>{const map=ref.current?.getMap();if(!ready||!map?.getSource(riskSource))return;selectFeature(map,p.region,p.layers.sample,previous.current,p.selectedId);previous.current=p.selectedId},[ready,p.selectedId,p.region,p.layers.sample]);
 useEffect(()=>{if(!ready)return;const bounds=p.region.cities.find(c=>c.id===p.city)?.bounds??p.region.bounds;ref.current?.fitBounds([[bounds.west,bounds.south],[bounds.east,bounds.north]],{padding:mapPadding(ref.current!.getMap().getContainer().clientWidth,ref.current!.getMap().getContainer().clientHeight,latest.current.detailHeight),duration:reduce?0:850})},[ready,p.city,p.region,reduce]);
 useEffect(()=>{if(!ready||!p.focus)return;ref.current?.flyTo({center:[p.focus.lng,p.focus.lat],zoom:13.5,duration:reduce?0:850,padding:mapPadding(ref.current!.getMap().getContainer().clientWidth,ref.current!.getMap().getContainer().clientHeight,latest.current.detailHeight)})},[ready,p.focus,reduce]);
 useEffect(()=>{const map=ref.current?.getMap();if(!map||!ready)return;const toggle=()=>{if(map.getLayer('kaali-3d'))map.setLayoutProperty('kaali-3d','visibility',threeD?'visible':'none')};toggle();map.on('style.load',toggle);map.easeTo({pitch:threeD?50:0,duration:reduce?0:600});return()=>{map.off('style.load',toggle)}},[ready,threeD,reduce]);
 useEffect(()=>{const map=ref.current?.getMap();if(!map)return;const observer=new ResizeObserver(()=>{const box=map.getContainer();map.resize();const focus=latest.current.focus;map.jumpTo({...(focus?{center:[focus.lng,focus.lat] as [number,number]}:{}),padding:mapPadding(box.clientWidth,box.clientHeight,latest.current.detailHeight)})});observer.observe(map.getContainer());return()=>observer.disconnect()},[ready]);
 useEffect(()=>{const map=ref.current?.getMap();if(!ready||!map)return;const box=map.getContainer();const focus=latest.current.focus;map.jumpTo({...(focus?{center:[focus.lng,focus.lat] as [number,number]}:{}),padding:mapPadding(box.clientWidth,box.clientHeight,p.detailHeight)})},[ready,p.detailHeight]);
 const points=useMemo(()=>({type:'FeatureCollection' as const,features:p.layers.help.filter(f=>f.geometry.type==='Point')}),[p.layers.help]);const roads=useMemo(()=>({type:'FeatureCollection' as const,features:p.layers.help.filter(f=>f.geometry.type==='LineString')}),[p.layers.help]);
 const accuracy=useMemo(()=>p.userPosition?circle([p.userPosition.lng,p.userPosition.lat],Math.min(p.userPosition.accuracy,50000)/1000,{steps:48,units:'kilometers'}):null,[p.userPosition]);
 const click=async(e:MapLayerMouseEvent)=>{const map=ref.current!.getMap(),f=e.features?.[0];if(!f)return;if(f.layer.id==='help-clusters'){const source=map.getSource('kaali-help') as GeoJSONSource;let zoom:number;try{zoom=await source.getClusterExpansionZoom(Number(f.properties.cluster_id))}catch{return}if(!map.getSource('kaali-help'))return;map.easeTo({center:(f.geometry as GeoJSON.Point).coordinates as [number,number],zoom,duration:reduce?0:500});return;}if(f.layer.id==='help-points'){setPopup({lat:e.lngLat.lat,lng:e.lngLat.lng,text:String(f.properties.name),source:String(f.properties.source)});return;}const r=p.layers.records.find(r=>r.id===String(f.id));if(r)p.onSelect(r)};
 const hover=(e:MapLayerMouseEvent)=>{if(popup?.source)return;const map=ref.current!.getMap();if(hoverId.current&&map.getSource(riskSource))map.setFeatureState(featureTarget(hoverId.current,p.region,p.layers.sample),{hover:false});const f=e.features?.find(f=>f.layer.id==='kaali-fill'||f.layer.id==='kaali-3d');hoverId.current=f?String(f.id):null;map.getCanvas().style.cursor=e.features?.length?'pointer':'';if(f){map.setFeatureState(featureTarget(String(f.id),p.region,p.layers.sample),{hover:true});const r=p.layers.records.find(r=>r.id===String(f.id));if(r)setPopup({lat:e.lngLat.lat,lng:e.lngLat.lng,text:`${r.name} · ${displayLevel(getScore(r,p.timeBand,p.day,p.crime,p.year))}${p.layers.sample?' · SAMPLE':''}`})}else setPopup(null)};
 return <><Map ref={ref} mapLib={maplibregl} initialViewState={{longitude:p.region.center.lng,latitude:p.region.center.lat,zoom:10}} mapStyle={style} maxBounds={[p.region.bounds.west,p.region.bounds.south,p.region.bounds.east,p.region.bounds.north]} attributionControl={false} onLoad={onLoad} onClick={click} onMouseMove={hover} onMouseLeave={()=>{if(!popup?.source)setPopup(null);const map=ref.current?.getMap();if(map&&hoverId.current&&map.getSource(riskSource))map.setFeatureState(featureTarget(hoverId.current,p.region,p.layers.sample),{hover:false});hoverId.current=null}} interactiveLayerIds={ready?interactive:[]} onError={e=>{if(!ref.current||/webgl|context lost|initialize/i.test(e.error.message)){p.onFatalError();return}p.onError('Map tiles could not load. Check your MapTiler key and network. Details and helplines remain available.')}} style={{width:'100%',height:'100%'}}>
 <AttributionControl position="bottom-right" compact={false} customAttribution={key?'© <a href="https://www.maptiler.com/copyright/">MapTiler</a> · © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>':'No basemap · illustrative geometry'}/>
 <Source id="kaali-help" type="geojson" data={points} cluster clusterMaxZoom={13} clusterRadius={40}><Layer id="help-clusters" type="symbol" filter={['has','point_count']} layout={{'icon-image':'kaali-icon-cluster','icon-size':1.7,'icon-allow-overlap':true}}/>{key&&<Layer id="help-cluster-count" type="symbol" filter={['has','point_count']} layout={{'text-field':['get','point_count_abbreviated'],'text-size':12}} paint={{'text-color':'#fff'}}/>}<Layer id="help-points" type="symbol" filter={['!', ['has','point_count']]} layout={{'icon-image':['concat','kaali-icon-',['get','kind']],'icon-allow-overlap':false,'icon-size':1.2}}/></Source>
 <Source id="kaali-roads" type="geojson" data={roads}><Layer id="help-roads" type="line" paint={{'line-color':'#508b88','line-width':3,'line-opacity':.7}}/></Source>
 {accuracy&&<Source id="user-accuracy" type="geojson" data={accuracy}><Layer id="accuracy-fill" type="fill" paint={{'fill-color':'#588f96','fill-opacity':.13}}/><Layer id="accuracy-line" type="line" paint={{'line-color':'#588f96','line-width':1}}/></Source>}{p.userPosition&&<Marker longitude={p.userPosition.lng} latitude={p.userPosition.lat}><div className="user-location" aria-label={`Your location, accuracy approximately ${Math.round(p.userPosition.accuracy)} metres`}/></Marker>}
 {p.districtPoints?.features.map(f=><Marker key={`district-${f.id}`} longitude={f.geometry.coordinates[0]} latitude={f.geometry.coordinates[1]}><button className="district-map-marker" aria-label={`${f.properties.name}: ${f.properties.count} historical recorded-head subtotal, ${displayPeriod(f.properties.year)}. Approximate reference point, not a safety score.`} onClick={e=>{e.stopPropagation();p.onDistrictSelect?.(f.id)}}><span>{f.properties.name}</span><b>{f.properties.count.toLocaleString('en-IN')}</b></button></Marker>)}
 {popup&&<Popup longitude={popup.lng} latitude={popup.lat} closeButton={Boolean(popup.source)} closeOnClick={false} onClose={()=>setPopup(null)}><div className="map-popup"><MapPin size={14}/><span>{popup.text}{popup.source&&<a href={popup.source} target="_blank" rel="noreferrer">OSM source ↗</a>}</span></div></Popup>}
 </Map>{key&&<a className="maptiler-logo" href="https://www.maptiler.com/" target="_blank" rel="noreferrer"><img src="https://api.maptiler.com/resources/logo.svg" alt="MapTiler" width="85" height="25"/></a>}<Glass className="map-navigation"><Button variant="ghost" size="icon" aria-label="Zoom in" onClick={()=>ref.current?.zoomIn({duration:reduce?0:250})}><Plus size={18}/></Button><Button variant="ghost" size="icon" aria-label="Zoom out" onClick={()=>ref.current?.zoomOut({duration:reduce?0:250})}><Minus size={18}/></Button><Button variant="ghost" size="icon" aria-label="Reset compass north" onClick={()=>ref.current?.resetNorth({duration:reduce?0:350})}><Compass size={18}/></Button><Button variant="ghost" size="icon" aria-label={threeD?'Switch to 2D map':'Switch to 3D risk map'} aria-pressed={threeD} onClick={()=>setThreeD(!threeD)}>{threeD?<Layers2 size={18}/>:<Box size={18}/>}</Button></Glass></>;
}


