import {lazy,Suspense,useEffect,useState} from 'react';
import {NavLink,Route,Routes,Navigate} from 'react-router-dom';
import {MotionConfig,motion} from 'framer-motion';
import {Shield,Sun,Moon,Phone,MapPin,Map,HeartHandshake,Database} from 'lucide-react';
import type {Region} from './types';
import {Button,Glass,Skeleton} from './components/ui';
const MapPage=lazy(()=>import('./components/MapPage'));
const HistoricalMap=lazy(()=>import('./pages/HistoricalMap'));
const Helplines=lazy(()=>import('./pages/Helplines'));
const Evidence=lazy(()=>import('./pages/Evidence'));
const DesignSystem=lazy(()=>import('./pages/DesignSystem'));
export default function App(){
 const [regions,setRegions]=useState<Region[]>([]),[regionId,setRegionId]=useState('delhi-ncr'),[error,setError]=useState(''),[jurisdiction,setJurisdiction]=useState('national');
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('kaali-theme')??localStorage.getItem('kaali:theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch{return 'light'}});
 const [lang,setLang]=useState(()=>{try{const saved=localStorage.getItem('kaali-language')??localStorage.getItem('kaali:language')??localStorage.getItem('kaali_lang');return saved==='hi'?'hi':'en'}catch{return 'en'}});
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('kaali-theme',theme)}catch{}},[theme]);
 useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('kaali-language',lang)}catch{}},[lang]);
 useEffect(()=>{fetch('/data/regions.json').then(r=>{if(!r.ok)throw Error('Region configuration unavailable');return r.json()}).then(setRegions).catch(e=>setError(e.message))},[]);
 const region=regions.find(r=>r.id===regionId)??regions[0];
 return <MotionConfig reducedMotion="user"><a className="skip-link" href="#main">Skip to content</a><Glass className="header"><NavLink to="/" className="brand" aria-label="Kaali home"><span className="brand-wordmark">Kaali</span></NavLink><nav aria-label="Main navigation"><NavLink to="/">{lang==='hi'?'नक्शा':'Explore'}</NavLink><NavLink to="/helplines">{lang==='hi'?'हेल्पलाइन':'Helplines'}</NavLink><NavLink to="/evidence">{lang==='hi'?'अपराध आँकड़े':'Crime data'}</NavLink></nav><span className="brand-tagline">Kaali- Symbol of strength, protection and fearlessness</span><div className="header-actions"><label className="region-select"><MapPin size={15}/><span className="sr-only">Region</span><select value={region?.id??regionId} onChange={e=>setRegionId(e.target.value)}>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><Button variant="ghost" size="icon" aria-label={`Switch to ${theme==='light'?'dark':'light'} theme`} onClick={()=>setTheme(theme==='light'?'dark':'light')}><motion.span key={theme} initial={{rotate:-35,opacity:0}} animate={{rotate:0,opacity:1}}>{theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</motion.span></Button><Button variant="ghost" size="icon" onClick={()=>setLang(lang==='en'?'hi':'en')} aria-label="Switch English / Hindi">{lang==='en'?'हिं':'EN'}</Button><Button asChild><a className="emergency" href="tel:112"><Phone size={15}/>{lang==='hi'?'कॉल':'Call'} 112</a></Button></div></Glass><Suspense fallback={<main className="page" id="main"><Skeleton/><Skeleton/></main>}>{error?<main className="page" id="main"><h1>We couldn’t load this region</h1><p role="alert">{error}</p><a href="tel:112">Call 112</a></main>:region?<Routes><Route path="/" element={<HistoricalMap theme={theme} region={region}/>}/><Route path="/methodology" element={<Navigate to="/evidence" replace/>}/><Route path="/neighbourhoods" element={<MapPage region={region} regions={regions} onRegion={setRegionId} theme={theme} lang={lang} onJurisdiction={setJurisdiction}/>}/><Route path="/helplines" element={<Helplines jurisdiction={jurisdiction} lang={lang}/>}/><Route path="/evidence" element={<Evidence region={region}/>}/><Route path="/about" element={<Navigate to="/evidence" replace/>}/><Route path="/design-system" element={<DesignSystem/>}/><Route path="*" element={<main className="page" id="main"><h1>Page not found</h1><NavLink to="/">Return to the map</NavLink></main>}/></Routes>:<main className="page" id="main"><Skeleton/></main>}</Suspense><Glass className="bottom-nav"><NavLink to="/"><Map size={20}/>Map</NavLink><NavLink to="/neighbourhoods?help=1"><HeartHandshake size={20}/>Nearby help</NavLink><NavLink to="/helplines"><Phone size={20}/>Helplines</NavLink><NavLink to="/evidence"><Database size={20}/>Crime data</NavLink></Glass></MotionConfig>;
}
