import {useEffect,useState} from 'react';
import {NavLink,Route,Routes} from 'react-router-dom';
import {Shield,Sun,Moon,Phone,MapPin,ArrowUpRight} from 'lucide-react';
import type {Region} from './types';
import MapPage from './components/MapPage';
export default function App(){
 const [regions,setRegions]=useState<Region[]>([]),[regionId,setRegionId]=useState('delhi-ncr'),[error,setError]=useState('');
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('aegis-theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch{return 'light'}});
 const [lang,setLang]=useState('en');
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('aegis-theme',theme)}catch{}},[theme]);
 useEffect(()=>{fetch('/data/regions.json').then(r=>{if(!r.ok)throw Error('Region configuration unavailable');return r.json()}).then(setRegions).catch(e=>setError(e.message))},[]);
 const region=regions.find(r=>r.id===regionId);
 return <><header className="header"><NavLink to="/" className="brand"><span className="brand-mark"><Shield size={23}/></span>aegis<span className="brand-divider"/><span className="brand-caption">A little more aware.</span></NavLink><nav aria-label="Main navigation"><NavLink to="/">Explore map</NavLink><NavLink to="/helplines">Helplines</NavLink><NavLink to="/about">Our methodology</NavLink></nav><div className="header-actions"><label className="region-select"><MapPin size={15}/><span className="sr-only">Region</span><select value={regionId} onChange={e=>setRegionId(e.target.value)}>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="icon-button" aria-label="Toggle theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button className="language" onClick={()=>setLang(lang==='en'?'hi':'en')} aria-label="Switch language">{lang==='en'?'हिं':'EN'}</button><a className="emergency" href="tel:112"><Phone size={15}/><span>Emergency: </span>112</a></div></header>{error?<main className="page"><h1>We couldn’t load this region</h1><p role="alert">{error}</p><a href="tel:112">Call 112</a></main>:region?<Routes><Route path="/" element={<MapPage region={region} regions={regions} onRegion={setRegionId} theme={theme} lang={lang}/>}/><Route path="/helplines" element={<main className="page"><p className="eyebrow">HELP IS HERE</p><h1>You don’t have to navigate it alone.</h1><a href="tel:112" className="primary">Call emergency services · 112 <ArrowUpRight size={18}/></a><p>Verified state resources are being added.</p></main>}/><Route path="/about" element={<main className="page"><h1>Awareness, grounded in evidence.</h1><p>Aegis shows model estimates, not guarantees. Limited data never means lower risk.</p></main>}/><Route path="*" element={<main className="page"><h1>Page not found</h1><NavLink to="/">Return to the map</NavLink></main>}/></Routes>:<main className="page" role="status">Loading region configuration…</main>}</>;
}
